
package Interfaz;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;

import java.text.DecimalFormat;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Map;
import java.util.Observable;
import java.util.Observer;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import project1.Articulo;
import project1.Empresa;
import project1.Proveedor;

/**
 *
 * @author polaco
 */
public class GuiCompras extends javax.swing.JFrame implements Observer {
    Empresa unaEmpresa;
    Boolean modificar = false;
    int nroFila;
    int stock;
    int kill = 0;
    Double Total = 0.0;
    public static Calendar fechaCompra;
    public static Proveedor unProveedor;
    public static DefaultTableModel modelo;


    /** Creates new form NewJFrame */
    public GuiCompras(Empresa unaEmpresa) {
        this.unaEmpresa = unaEmpresa;
        initComponents();
        actualizarComboProveedor();
        Date fechaActual = new Date();
        GregorianCalendar hoy = new GregorianCalendar();
        hoy.add(Calendar.DAY_OF_YEAR, 0);
        txtDate.setMaxSelectableDate(hoy.getTime());
        txtDate.setCalendar(hoy);
        txtDate.getDateEditor().getUiComponent().setEnabled(false);
        actualizarComboProveedor();
        unaEmpresa.addObserver(this);
        reloj();
        lblUsuarioActual1.setText(GuiIngresar.getUsuario());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPopupMenu1 = new javax.swing.JPopupMenu();
        MenuModificar = new javax.swing.JMenuItem();
        MenuEliminar = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        lblProveedor = new javax.swing.JLabel();
        cmbProveedor = (new JComboBox(unaEmpresa.getProveedores().values().toArray()));
        btnAgregarProveedor = new javax.swing.JButton();
        btnSeleccion = new javax.swing.JButton();
        lblFechaVenta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVenta = new javax.swing.JTable();
        panel1 = new javax.swing.JPanel();
        lblCodBarra = new javax.swing.JLabel();
        txtCodigodeBarra = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnAgregarArticulo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMonto = new java.awt.TextField();
        lblFormaPago4 = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFormaPago6 = new javax.swing.JLabel();
        txtMonto1 = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        btnGuardarNueVenta1 = new javax.swing.JButton();
        btnCancelarVenta = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblUsuarioActual1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        MenuModificar.setText("Modificar");
        MenuModificar.setToolTipText("");
        MenuModificar.setComponentPopupMenu(jPopupMenu1);
        MenuModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuModificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MenuModificar);
        MenuModificar.getAccessibleContext().setAccessibleParent(jPopupMenu1);

        MenuEliminar.setText("Eliminar");
        MenuEliminar.setComponentPopupMenu(jPopupMenu1);
        MenuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MenuEliminar);
        MenuEliminar.getAccessibleContext().setAccessibleParent(jPopupMenu1);

        jPopupMenu1.getAccessibleContext().setAccessibleParent(tblVenta);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Compras");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/iconos/iconoprograma.png")));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblProveedor.setText("Proveedor");

        cmbProveedor.setModel((new javax.swing.DefaultComboBoxModel(unaEmpresa.getProveedores().values().toArray())));

        btnAgregarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1409705665_add.png"))); // NOI18N
        btnAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProveedorActionPerformed(evt);
            }
        });

        btnSeleccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1412329438_685082-Search-16.png"))); // NOI18N
        btnSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionActionPerformed(evt);
            }
        });

        lblFechaVenta.setText("Fecha");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnAgregarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(566, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblFechaVenta))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFechaVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregarProveedor)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProveedor)
                            .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );

        tblVenta.setAutoCreateRowSorter(true);
        tblVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo de Barra", "Descripcion", "Talle", "Color", "Cantidad", "Precio", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVenta.setComponentPopupMenu(jPopupMenu1);
        tblVenta.getTableHeader().setReorderingAllowed(false);
        tblVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVenta);
        tblVenta.getColumnModel().getColumn(0).setHeaderValue("Codigo de Barra");
        tblVenta.getColumnModel().getColumn(1).setHeaderValue("Descripcion");
        tblVenta.getColumnModel().getColumn(2).setHeaderValue("Talle");
        tblVenta.getColumnModel().getColumn(3).setHeaderValue("Color");
        tblVenta.getColumnModel().getColumn(4).setHeaderValue("Cantidad");
        tblVenta.getColumnModel().getColumn(5).setHeaderValue("Precio");
        tblVenta.getColumnModel().getColumn(6).setHeaderValue("Total");

        lblCodBarra.setText("Codigo de Barra*");

        txtCodigodeBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigodeBarraActionPerformed(evt);
            }
        });
        txtCodigodeBarra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigodeBarraFocusLost(evt);
            }
        });
        txtCodigodeBarra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigodeBarraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigodeBarraKeyTyped(evt);
            }
        });

        lblCantidad.setText("cantidad*");

        txtCantidad.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCantidadCaretUpdate(evt);
            }
        });
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        lblPrecio.setText("precio*");

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        txtPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioFocusLost(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1409705665_add.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnAgregarArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1409705665_add.png"))); // NOI18N
        btnAgregarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArticuloActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/delete-icon.png"))); // NOI18N
        btnCancelar.setText("cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblTotal.setBackground(new java.awt.Color(0, 0, 0));
        lblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Total");

        jLabel2.setText("Descuento");

        txtMonto.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtMontoTextValueChanged(evt);
            }
        });
        txtMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMontoFocusLost(evt);
            }
        });
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });

        lblFormaPago4.setText("Monto");

        lblTotal1.setBackground(new java.awt.Color(0, 0, 0));
        lblTotal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblTotal1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setText("Descuento");

        lblFormaPago6.setText("Monto");

        txtMonto1.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtMonto1TextValueChanged(evt);
            }
        });
        txtMonto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonto1ActionPerformed(evt);
            }
        });
        txtMonto1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMonto1FocusLost(evt);
            }
        });
        txtMonto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMonto1KeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Precio C/U");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1412329438_685082-Search-16.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblSubTotal.setBackground(new java.awt.Color(0, 0, 0));
        lblSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblSubTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("subtotal");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(lblCodBarra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(txtCodigodeBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(108, 108, 108)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrecio)
                                    .addComponent(jLabel3))
                                .addGap(27, 27, 27)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(lblFormaPago6))
                                    .addComponent(txtMonto1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(txtPrecio))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(114, 114, 114)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblFormaPago4)
                                        .addGap(60, 60, 60))))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(112, 112, 112)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(53, 53, 53)
                        .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregarArticulo)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodBarra)
                        .addComponent(txtCodigodeBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFormaPago6)
                                    .addComponent(btnCancelar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMonto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnAgregar)
                        .addGap(29, 29, 29)))
                .addContainerGap())
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(17, 17, 17)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(lblFormaPago4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateFocusLost(evt);
            }
        });
        txtDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDateKeyTyped(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnGuardarNueVenta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1405280090_15_Tick_32x32.png"))); // NOI18N
        btnGuardarNueVenta1.setText("aceptar");
        btnGuardarNueVenta1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGuardarNueVenta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarNueVenta1MouseClicked(evt);
            }
        });
        btnGuardarNueVenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNueVenta1ActionPerformed(evt);
            }
        });

        btnCancelarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1404956598_Delete.png"))); // NOI18N
        btnCancelarVenta.setText("Cancelar");
        btnCancelarVenta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarVentaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnGuardarNueVenta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 924, Short.MAX_VALUE)
                .addComponent(btnCancelarVenta)
                .addGap(115, 115, 115))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarNueVenta1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btnCancelarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel13.setText("Usuario: ");

        lblUsuarioActual1.setText("label");

        jLabel14.setText("fecha:");

        lblFecha.setText("Usuario: ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarioActual1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha)
                .addGap(82, 82, 82))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel14)
                .addComponent(lblFecha)
                .addComponent(jLabel13)
                .addComponent(lblUsuarioActual1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void tblVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVentaMouseClicked
        if ((evt.getModifiers() & InputEvent.BUTTON3_MASK) == InputEvent.BUTTON3_MASK) {
            jPopupMenu1.setVisible(true);
        }
    }//GEN-LAST:event_tblVentaMouseClicked

    private void txtCodigodeBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigodeBarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigodeBarraActionPerformed

    private void txtCodigodeBarraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigodeBarraFocusLost
        preparado();
    }//GEN-LAST:event_txtCodigodeBarraFocusLost

    private void txtCodigodeBarraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigodeBarraKeyPressed

    }//GEN-LAST:event_txtCodigodeBarraKeyPressed

    private void txtCodigodeBarraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigodeBarraKeyTyped
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            txtCantidad.requestFocus();
        }
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (txtCodigodeBarra.getText().length() >= 13) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigodeBarraKeyTyped

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (txtCantidad.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.')) {
            evt.consume();
        }
        if (c == '.' && txtPrecio.getText().contains(".")) {
            evt.consume();
            int i = txtPrecio.getText().indexOf(".");
            txtPrecio.setCaretPosition(i + 1);
        }
        if (txtPrecio.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (!txtCodigodeBarra.getText().equals("") && (!txtCantidad.getText().equals(""))) {
            CargaTabla();
            txtCodigodeBarra.setEnabled(true);
            if (modificar == true) {
                DefaultTableModel modelo = (DefaultTableModel) tblVenta.getModel();
                modelo.removeRow(tblVenta.getSelectedRow());
                modificar = false;
            }
            jButton1.setEnabled(true);
            txtCodigodeBarra.setEnabled(true);
            txtCantidad.setText("");
            txtPrecio.setText("");
            txtCodigodeBarra.setText("");
            /*if (txtPrecio.getText().equals("")) {
        lblPrecio.setForeground(Color.red);
    } else {
        lblPrecio.setForeground(Color.black);
    }
    if (txtCantidad.getText().equals("")) {
        lblCantidad.setForeground(Color.red);
    } else {
        lblCantidad.setForeground(Color.black);
    }
    if (txtCodigodeBarra.getText().equals("")) {
        lblCodBarra.setForeground(Color.red);
    } else {
        lblCodBarra.setForeground(Color.black);
    }*/
        } else {
            JOptionPane.showMessageDialog(null, "no ingreso codigo de barra o cantidad");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAgregarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarArticuloActionPerformed
        GuiArticulos vArt = new GuiArticulos(unaEmpresa);
        vArt.setVisible(true);
    }//GEN-LAST:event_btnAgregarArticuloActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtCodigodeBarra.setEnabled(true);
        jButton1.setEnabled(true);
        modificar = false;
        txtCodigodeBarra.setText("");
        txtPrecio.setText("");
        txtCantidad.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarNueVenta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarNueVenta1MouseClicked

    }//GEN-LAST:event_btnGuardarNueVenta1MouseClicked

    private void btnGuardarNueVenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNueVenta1ActionPerformed
        Guardar();
    }//GEN-LAST:event_btnGuardarNueVenta1ActionPerformed

    private void btnCancelarVentaMouseClicked(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_btnCancelarVentaMouseClicked
        this.dispose();
    }

    private void MenuModificarActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_MenuModificarActionPerformed//GEN-LAST:event_btnCancelarVentaMouseClicked
        nroFila = tblVenta.getSelectedRow();//GEN-FIRST:event_MenuModificarActionPerformed
        if (nroFila == -1) {
            JOptionPane.showMessageDialog(null, "seleccione una fila");
        } else {
            jButton1.setEnabled(false);
            txtCodigodeBarra.setEnabled(false);
            DefaultTableModel modelo = (DefaultTableModel) tblVenta.getModel();
            txtCantidad.setText(modelo.getValueAt(nroFila, 4).toString());
            txtCodigodeBarra.setText(modelo.getValueAt(nroFila, 0).toString());
            txtPrecio.setText(modelo.getValueAt(nroFila, 5).toString());
            modificar = true;
        } 
    }//GEN-LAST:event_MenuModificarActionPerformed

    private void MenuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEliminarActionPerformed
        int i = tblVenta.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "seleccione una fila");
        } else {
            DefaultTableModel modelo = (DefaultTableModel) tblVenta.getModel();
            modelo.removeRow(i);
        }
    }//GEN-LAST:event_MenuEliminarActionPerformed

    private void txtCantidadCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCantidadCaretUpdate

    }//GEN-LAST:event_txtCantidadCaretUpdate

    private void txtMontoTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtMontoTextValueChanged

    }//GEN-LAST:event_txtMontoTextValueChanged

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
        char c = evt.getKeyChar();
        double j;
        if (txtMonto.getText().equals("")) {
            txtMonto.setText("0.0");
        }
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.')) {
            evt.consume();
        } else {
            kill = 0;
        }
        if (c == '.' && txtMonto.getText().contains(".")) {
            evt.consume();
            int i = txtMonto.getText().indexOf(".");
            txtMonto.setCaretPosition(i + 1);
        }
        if (txtMonto.getText().length() >= 13) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMontoKeyTyped

    private void btnAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProveedorActionPerformed
        GuiProveedores gui = new GuiProveedores(unaEmpresa);
        gui.setVisible(true);
    }//GEN-LAST:event_btnAgregarProveedorActionPerformed

    private void txtMontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoFocusLost
        double j = (Double.parseDouble(txtMonto.getText()));
        if (j > Total) {
            txtMonto.setText(String.valueOf(Total));
        }
        j = (Double.parseDouble(txtMonto.getText()));
        double i = (Double.parseDouble(lblSubTotal.getText()));
        lblTotal.setText(String.valueOf(i-j));
    }//GEN-LAST:event_txtMontoFocusLost

    private void txtMonto1TextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtMonto1TextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonto1TextValueChanged

    private void txtMonto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonto1ActionPerformed

    private void txtMonto1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMonto1FocusLost
        double j = (Double.parseDouble(txtMonto1.getText()));
        if (j > Total) {
            txtMonto1.setText(String.valueOf(Total));
        }
        if (!txtMonto1.getText().equals("")) {
            lblTotal1.setText(String.valueOf(Double.parseDouble(txtPrecio.getText()) - Double.parseDouble(txtMonto1.getText())));
        }
    }//GEN-LAST:event_txtMonto1FocusLost

    private void txtMonto1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMonto1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonto1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String unArt = "";
        GuiSeleccionArt filtro = new GuiSeleccionArt(this, true, unaEmpresa, unArt);
        filtro.setVisible(true);
        txtCodigodeBarra.setText(filtro.getUnArt());
        preparado();
        txtCantidad.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionActionPerformed
        Proveedor unPro = null;
        GuiSeleccionProveedor filtro = new GuiSeleccionProveedor(this, true, unaEmpresa, unPro);
        filtro.setVisible(true);
        unPro = filtro.getUnPro();
        cmbProveedor.setSelectedItem(unPro);
    }//GEN-LAST:event_btnSeleccionActionPerformed

    private void txtPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioFocusLost
        lblTotal1.setText(String.valueOf(Double.parseDouble(txtPrecio.getText()) - Double.parseDouble(txtMonto1.getText())));
    }//GEN-LAST:event_txtPrecioFocusLost

    private void txtDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusLost

    }//GEN-LAST:event_txtDateFocusLost

    private void txtDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateKeyTyped

    }//GEN-LAST:event_txtDateKeyTyped
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiCompras().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuEliminar;
    private javax.swing.JMenuItem MenuModificar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarArticulo;
    private javax.swing.JButton btnAgregarProveedor;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarVenta;
    private javax.swing.JButton btnGuardarNueVenta1;
    private javax.swing.JButton btnSeleccion;
    private javax.swing.JComboBox cmbProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCodBarra;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaVenta;
    private javax.swing.JLabel lblFormaPago4;
    private javax.swing.JLabel lblFormaPago6;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblUsuarioActual1;
    private javax.swing.JPanel panel1;
    private javax.swing.JTable tblVenta;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigodeBarra;
    private com.toedter.calendar.JDateChooser txtDate;
    private java.awt.TextField txtMonto;
    private java.awt.TextField txtMonto1;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
   
    public void CargaTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblVenta.getModel();
        Map articulos = unaEmpresa.getArticulos();
        Articulo unArt = (Articulo) articulos.get(txtCodigodeBarra.getText().toString());
        String detalle = (unArt.getNombre() + " " + unArt.getUnaMarca());
        double total = (Double.parseDouble(txtCantidad.getText()) * Double.parseDouble(txtPrecio.getText()));
        modelo.addRow(new Object[] { (unArt.getCodBarra()), detalle, (unArt.getTalle()), (unArt.getColor()), (txtCantidad.getText()), (lblTotal1.getText()), (total) });
        Double j = 0.0;
        int filas = tblVenta.getRowCount();
        for (int i = 0; filas > i; i++)
            j = j + Double.parseDouble(modelo.getValueAt(i, 6).toString());
        lblTotal.setText(String.valueOf(j));
        Total = j;
    }

    public void Guardar() {
        fechaCompra = txtDate.getCalendar();
        if (!cmbProveedor.getSelectedItem().equals(""))
            if (this.tblVenta.getRowCount() != 0) {
                unProveedor = (Proveedor) cmbProveedor.getSelectedItem();
                modelo = (DefaultTableModel) tblVenta.getModel();
                Total = Double.parseDouble(lblTotal.getText());
                GuiPago unaGuiTipoPago = new GuiPago(new javax.swing.JDialog(), true, unaEmpresa, true, Total);
                unaGuiTipoPago.setVisible(true);
                int filas = tblVenta.getRowCount();
                for (int i = 0; filas > i; i++)
                    modelo.removeRow(0);
            } else {
                JOptionPane.showMessageDialog(null, "no cargo ningun articulo");
            }
        else {
            JOptionPane.showMessageDialog(null, "no ingreso el proveedor");
        }
    }

    public void actualizarComboProveedor() {
        cmbProveedor.setModel(new javax.swing.DefaultComboBoxModel(unaEmpresa.getProveedores().values().toArray()));
    }

    /*public void actualizarComboEmpleado() {
        Map hijos = new HashMap();
        for (Empleado unEmp : unaEmpresa.getEmpleados().values()) {
            if (unEmp.isEstado()) {
                hijos.put(unEmp.getNroDocEmppleado(), unEmp);
            }
        }
        cmbEmpleado.setModel(new javax.swing.DefaultComboBoxModel(hijos.values().toArray()));
    }*/

    @Override
    public void update(Observable observable, Object object) {
        actualizarComboProveedor();
        //actualizarComboEmpleado();
    }

    private void reloj() {
        javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent ae) {
                lblFecha.setText(Calendar.getInstance().getTime().toLocaleString());
            }
        });
        timer.start();
    }

    public void preparado() {
        if (!txtCodigodeBarra.getText().equals("")) {
            if ((unaEmpresa.getArticulos().containsKey(txtCodigodeBarra.getText()))) {
                DefaultTableModel modelo = (DefaultTableModel) tblVenta.getModel();
                int filas = tblVenta.getRowCount();
                Boolean error = false;
                for (int i = 0; filas > i; i++) {
                    if (txtCodigodeBarra.getText().equals(modelo.getValueAt(i, 0).toString()) && modificar == false) {
                        error = true;
                    }
                }
                if (error) {
                    JOptionPane.showMessageDialog(null, "El articulo ya esta cargado");
                    lblNombre.setText("El articulo ya esta cargado");
                    lblNombre.setForeground(Color.red);
                    lblMarca.setText("");
                    btnAgregar.setEnabled(false);
                } else {
                    txtCodigodeBarra.setEnabled(false);
                    txtCantidad.setEnabled(true);
                    txtCantidad.setEnabled(true);
                    btnAgregar.setEnabled(true);
                    Map articulos = unaEmpresa.getArticulos();
                    Articulo unArt = (Articulo) articulos.get(txtCodigodeBarra.getText().toString());
                    btnAgregar.setEnabled(true);
                    lblMarca.setText("Nombre: " + unArt.getNombre());
                    lblMarca.setForeground(Color.green);
                    lblNombre.setText("Marca: " + unArt.getUnaMarca().getNombreMarca());
                    lblNombre.setForeground(Color.green);
                    txtPrecio.setText(String.valueOf(unArt.getPrecioVenta()));
                    txtPrecio.setText(String.valueOf(unArt.getPrecioVenta()));
                    txtCantidad.setText("");
                    stock = unArt.getStock();
                    jButton1.setEnabled(false);
                    txtMonto1.setText("0.0");
                    lblTotal1.setText(String.valueOf(Double.parseDouble(txtPrecio.getText()) - Double.parseDouble(txtMonto1.getText())));
                }
            } else {
                JOptionPane.showMessageDialog(null, "no existe articulo.");
                lblNombre.setText("no existe articulo");
                lblNombre.setForeground(Color.red);
                lblMarca.setText("");
                btnAgregar.setEnabled(false);
            }
        }
    }
}
