
package Interfaz;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import project1.Caja;
import project1.Empresa;
import project1.MovimientoCaja;
import project1.Pago;

/**
 *
 * @author polaco
 */
public class GuiCierreCaja1 extends javax.swing.JFrame {
    Empresa unaEmpresa;
    /** Creates new form CierreCaja */
    public GuiCierreCaja1(Empresa unaEmpresa) {
        this.unaEmpresa = unaEmpresa;
        initComponents();
        cargar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        dateUtil1 = new com.toedter.calendar.DateUtil();
        jPanel1 = new javax.swing.JPanel();
        lblSaldoEsperado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSaldoEsperado = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFaltante = new javax.swing.JTextArea();
        lblFaltante = new javax.swing.JLabel();
        lblSaldoSistema = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelarModelo = new javax.swing.JButton();
        btnCancelarModelo1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstFormaPago = new javax.swing.JList();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cierre Caja");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/iconos/iconoprograma.png")));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Efectivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        lblSaldoEsperado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1410385110_safe.png"))); // NOI18N
        lblSaldoEsperado.setText("Saldo Real");

        txtSaldoEsperado.setText("0.0");
        txtSaldoEsperado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoEsperadoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtSaldoEsperado);

        txtFaltante.setColumns(20);
        txtFaltante.setRows(5);
        txtFaltante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFaltanteKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtFaltante);

        lblFaltante.setText("Descripcion por Faltante");

        lblSaldoSistema.setText("Saldo de Sistema");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1404939333_Dollar.png"))); // NOI18N
        jLabel2.setText("Saldo de Sistema");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(lblFaltante))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(lblSaldoEsperado))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSaldoSistema)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblSaldoSistema))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSaldoEsperado)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblFaltante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnCancelarModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1405280090_15_Tick_32x32.png"))); // NOI18N
        btnCancelarModelo.setText("Confirmar");
        btnCancelarModelo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarModeloActionPerformed(evt);
            }
        });

        btnCancelarModelo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1404956598_Delete.png"))); // NOI18N
        btnCancelarModelo1.setText("Cancelar");
        btnCancelarModelo1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelarModelo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarModelo1MouseClicked(evt);
            }
        });
        btnCancelarModelo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarModelo1ActionPerformed(evt);
            }
        });

        lstFormaPago.setBorder(javax.swing.BorderFactory.createTitledBorder("Otras Formas de Pago"));
        lstFormaPago.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstFormaPago);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnCancelarModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarModelo1)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jDayChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDayChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void btnCancelarModelo1MouseClicked(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_btnCancelarModelo1MouseClicked
        this.dispose();
    } //GEN-LAST:event_btnCancelarModelo1MouseClicked

    private void btnCancelarModeloActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnCancelarModeloActionPerformed
        try {
            double otros = 0.0;
            double saldoSistema = 0.0;
            for (int i = 2; i <= unaEmpresa.getTiposPagos().size(); i++) {
                for (MovimientoCaja unMov : cajaAbierta().getMovimientosCaja().values()) {
                    for (Object unPago : unMov.getUnaVenta().getPagosVentas().values()) {
                        Pago unP = (Pago) unPago;
                        if (unP.getUnTipoPago() == unaEmpresa.getTiposPagos().get(1)) {
                            saldoSistema += unP.getMonto();
                        } else if (unP.getUnTipoPago() == unaEmpresa.getTiposPagos().get(i)) {
                            otros += unP.getMonto();
                        }
                    }

                }
                unaEmpresa.agregarCierreCaja(cajaAbierta().getCodCaja(), otros, 0.0, unaEmpresa.getTiposPagos().get(i), "");
            }
            unaEmpresa.agregarCierreCaja(cajaAbierta().getCodCaja(), saldoSistema, Double.parseDouble(txtSaldoEsperado.getText()), unaEmpresa.getTiposPagos().get(1), txtFaltante.getText());
            JOptionPane.showMessageDialog(null, "se cerro la caja con exito");
            unaEmpresa.cerrarCaja(cajaAbierta());
            //unaEmpresa.getCajas().get(codCaja()).setCajaAbierta(false);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    } //GEN-LAST:event_btnCancelarModeloActionPerformed

    private void btnCancelarModelo1ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnCancelarModelo1ActionPerformed
        //unaEmpresa.agregarCierreCaja(1, codTurno, codCierreCaja, saldoSistema, saldoReal, tipospago, descripcion);
    } //GEN-LAST:event_btnCancelarModelo1ActionPerformed

    private void txtSaldoEsperadoKeyTyped(java.awt.event.KeyEvent evt) { //GEN-FIRST:event_txtSaldoEsperadoKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.')) {
            evt.consume();
        }
        if (c == '.' && txtSaldoEsperado.getText().contains(".")) {
            evt.consume();
        }
        if (txtSaldoEsperado.getText().length() >= 13) {
            evt.consume();
        }
    } //GEN-LAST:event_txtSaldoEsperadoKeyTyped

    private void txtFaltanteKeyTyped(java.awt.event.KeyEvent evt) { //GEN-FIRST:event_txtFaltanteKeyTyped
        if (txtFaltante.getText().length() >= 100) {
            evt.consume();
        }
    } //GEN-LAST:event_txtFaltanteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiCierreCaja1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiCierreCaja1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiCierreCaja1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiCierreCaja1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiCierreCaja(unaEmpresa).setVisible(true);
            }
        })*/;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarModelo;
    private javax.swing.JButton btnCancelarModelo1;
    private com.toedter.calendar.DateUtil dateUtil1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblFaltante;
    private javax.swing.JLabel lblSaldoEsperado;
    private javax.swing.JLabel lblSaldoSistema;
    private javax.swing.JList lstFormaPago;
    private javax.swing.JTextArea txtFaltante;
    private javax.swing.JTextPane txtSaldoEsperado;
    // End of variables declaration//GEN-END:variables


    public void cargar() {
        Double saldoSistema = cajaAbierta().getSaldoInicial();
        double otros = 0.0;
        DefaultListModel modelo = new DefaultListModel();
        for (int i = 2; i <= unaEmpresa.getTiposPagos().size(); i++) {
            for (MovimientoCaja unMov : cajaAbierta().getMovimientosCaja().values()) {
                for (Object unPago : unMov.getUnaVenta().getPagosVentas().values()) {
                    Pago unP = (Pago) unPago;
                    if (unP.getUnTipoPago() == unaEmpresa.getTiposPagos().get(1)) {
                        saldoSistema += unP.getMonto();
                    } else if (unP.getUnTipoPago() == unaEmpresa.getTiposPagos().get(i)) {
                        otros += unP.getMonto();
                    }
                }

            }
            modelo.addElement(unaEmpresa.getTiposPagos().get(i) + " = " + otros);
        }
        lblSaldoSistema.setText(String.valueOf(saldoSistema));
        lstFormaPago.setModel(modelo);
    }

    public Caja cajaAbierta() {
        Caja unaCa = null;
        for (Caja unaCaja : unaEmpresa.getCajas().values()) {
            if (unaCaja.isCajaAbierta()) {
                unaCa = unaCaja;
            }
        }
        return unaCa;
    }
}
