
package Interfaz;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;

import java.util.Calendar;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.Observable;
import java.util.Observer;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import project1.Empresa;
import project1.Proveedor;

/**
 *
 * @author polaco
 */
public class GuiProveedores extends javax.swing.JFrame implements Observer {
    Empresa unaEmpresa;
    //Collection proveedores = new LinkedList();


    /** Creates new form Proveedor */
    public GuiProveedores(Empresa unaEmpresa) {
        this.unaEmpresa = unaEmpresa;
        initComponents();
        reloj();
        lblUsuarioActual2.setText(GuiIngresar.getUsuario());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuEliminar = new javax.swing.JMenuItem();
        menuModificar = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblRazonSocial = new javax.swing.JLabel();
        lblCuil = new javax.swing.JLabel();
        lblDomicilio = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCuil = new javax.swing.JTextField();
        txtDomicilio = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        txtBusqueda = new javax.swing.JTextPane();
        lblBusqueda = new javax.swing.JLabel();
        lblCriterioBusqueda = new javax.swing.JLabel();
        cmbCriterioProveedor = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();
        btnGuardarCerPro1 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblUsuarioActual2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblFecha1 = new javax.swing.JLabel();

        menuEliminar.setText("Eliminar");
        menuEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEliminarMouseClicked(evt);
            }
        });
        menuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuEliminar);
        menuEliminar.getAccessibleContext().setAccessibleParent(jPopupMenu1);

        menuModificar.setText("Modificar");
        menuModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuModificarMouseClicked(evt);
            }
        });
        menuModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuModificar);
        menuModificar.getAccessibleContext().setAccessibleParent(jPopupMenu1);

        jPopupMenu1.getAccessibleContext().setAccessibleParent(tblProveedores);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Proveedores");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/iconos/iconoprograma.png")));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        lblRazonSocial.setText("Razon Social*");

        lblCuil.setText("CUIL*");

        lblDomicilio.setText("Domicilio");

        lblTelefono.setText("Telefono");

        lblSaldo.setText("Saldo*");

        txtRazonSocial.setNextFocusableComponent(txtCuil);
        txtRazonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRazonSocialKeyTyped(evt);
            }
        });

        txtTelefono.setNextFocusableComponent(txtSaldo);
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        txtCuil.setNextFocusableComponent(txtDomicilio);
        txtCuil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCuilFocusLost(evt);
            }
        });
        txtCuil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuilKeyTyped(evt);
            }
        });

        txtDomicilio.setNextFocusableComponent(txtTelefono);
        txtDomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDomicilioKeyTyped(evt);
            }
        });

        txtSaldo.setNextFocusableComponent(btnGuardarCerPro1);
        txtSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRazonSocial)
                    .addComponent(lblCuil)
                    .addComponent(lblDomicilio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuil, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblSaldo)
                        .addGap(68, 68, 68)
                        .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 186, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRazonSocial)
                            .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(lblCuil))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTelefono)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(53, 53, 53))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSaldo)
                                .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(2, 2, 2))))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDomicilio)
                    .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        jScrollPane16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jScrollPane16KeyTyped(evt);
            }
        });

        txtBusqueda.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBusquedaCaretUpdate(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });
        jScrollPane16.setViewportView(txtBusqueda);

        lblBusqueda.setText("Busqueda:");

        lblCriterioBusqueda.setText("Criterio de Busqueda:");

        cmbCriterioProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Busqueda Inteligente", "CUIT", "Razon Social", "Domicilio" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBusqueda)
                    .addComponent(lblCriterioBusqueda))
                .addGap(62, 62, 62)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCriterioProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCriterioBusqueda)
                    .addComponent(cmbCriterioProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBusqueda, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        tblProveedores.setAutoCreateRowSorter(true);
        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Razon Social", "CUIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProveedores.setComponentPopupMenu(jPopupMenu1);
        tblProveedores.getTableHeader().setReorderingAllowed(false);
        tblProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProveedores);
        tblProveedores.getColumnModel().getColumn(0).setHeaderValue("Razon Social");
        tblProveedores.getColumnModel().getColumn(1).setHeaderValue("CUIL");

        btnGuardarCerPro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1404955973_Save.png"))); // NOI18N
        btnGuardarCerPro1.setText("Guardar");
        btnGuardarCerPro1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGuardarCerPro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCerPro1ActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1404956598_Delete.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnGuardarCerPro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(233, 233, 233))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCerPro1)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel15.setText("Usuario: ");

        lblUsuarioActual2.setText("label");

        jLabel16.setText("fecha:");

        lblFecha1.setText("Usuario: ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarioActual2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha1)
                .addGap(114, 114, 114))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel16)
                .addComponent(lblFecha1)
                .addComponent(jLabel15)
                .addComponent(lblUsuarioActual2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }//GEN-END:initComponents


    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtCuil.setEnabled(true);
        limpiar();
        CargaTabla(unaEmpresa.getProveedores());
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        CargaTabla(unaEmpresa.getProveedores());
    }//GEN-LAST:event_formWindowActivated

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
   
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void jScrollPane16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane16KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane16KeyTyped

    private void tblProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProveedoresMouseClicked
        if ((evt.getModifiers() & InputEvent.BUTTON3_MASK) == InputEvent.BUTTON3_MASK) {
            jPopupMenu1.setVisible(true);
        }
    }//GEN-LAST:event_tblProveedoresMouseClicked

    private void menuModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuModificarMouseClicked

    }//GEN-LAST:event_menuModificarMouseClicked

    private void menuEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEliminarMouseClicked
        
    }//GEN-LAST:event_menuEliminarMouseClicked

    private void txtCuilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuilKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (txtCuil.getText().length() >= 11) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCuilKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (txtTelefono.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtSaldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.')) {
            evt.consume();
        }
        if (c == '.' && txtSaldo.getText().contains(".")) {
            evt.consume();
            int i = txtSaldo.getText().indexOf(".");
            txtSaldo.setCaretPosition(i + 1);
        }
        if (txtSaldo.getText().length() >= 7) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSaldoKeyTyped

    private void btnGuardarCerPro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCerPro1ActionPerformed
        Boolean hayError = false;
        try {
            if (ValidaCuit(txtCuil.getText())){
            if ((!txtCuil.getText().equals("")) && (!txtRazonSocial.getText().equals("")) && (!txtSaldo.getText().equals(""))) {
                try {
                    lblCuil.setForeground(Color.black);
                    lblDomicilio.setForeground(Color.black);
                    lblRazonSocial.setForeground(Color.black);
                    lblSaldo.setForeground(Color.black);
                    lblTelefono.setForeground(Color.black);
                    if (txtCuil.isEnabled()) {
                        unaEmpresa.agregarProveedor(txtRazonSocial.getText(), txtCuil.getText().toString(), txtTelefono.getText().toString(),
                                                    txtDomicilio.getText().toString(), Double.parseDouble(txtSaldo.getText().toString()));
                        limpiar();
                        CargaTabla(unaEmpresa.getProveedores());
                        JOptionPane.showMessageDialog(null, "El proveedor se cargo con exito");

                    } else {
                        unaEmpresa.modificarProveedor(txtRazonSocial.getText().toString(), txtCuil.getText().toString(), txtTelefono.getText().toString(),
                                                      txtTelefono.getText().toString(), Double.parseDouble(txtSaldo.getText().toString()));
                        limpiar();
                        CargaTabla(unaEmpresa.getProveedores());
                        JOptionPane.showMessageDialog(null, "El proveedor se modifico con exito");
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            } else {
                if (txtCuil.getText().equals("")) {
                    lblCuil.setForeground(Color.red);
                    hayError = true;
                } else {
                    lblCuil.setForeground(Color.black);
                }
                if (txtDomicilio.getText().equals("")) {
                    lblDomicilio.setForeground(Color.red);
                    hayError = true;
                } else {
                    lblDomicilio.setForeground(Color.black);
                }
                if (txtRazonSocial.getText().equals("")) {
                    lblRazonSocial.setForeground(Color.red);
                    hayError = true;
                } else {
                    lblRazonSocial.setForeground(Color.black);
                }
                if (txtSaldo.getText().equals("")) {
                    lblSaldo.setForeground(Color.red);
                    hayError = true;
                } else {
                    lblSaldo.setForeground(Color.black);
                }
                if (txtTelefono.getText().equals("")) {
                    lblTelefono.setForeground(Color.red);
                    hayError = true;
                } else {
                    lblTelefono.setForeground(Color.black);
                }
                /*if (txtTelefono.getText().equals("") && (txtDomicilio.getText().equals(""))) {
                    JOptionPane.showMessageDialog(null, "se cargo con exito6");
                }*/

            }
            }else
            JOptionPane.showMessageDialog(null, "CUIT invalido");
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnGuardarCerPro1ActionPerformed

    private void txtRazonSocialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonSocialKeyTyped
        if (txtRazonSocial.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRazonSocialKeyTyped

    private void txtDomicilioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDomicilioKeyTyped
        if (txtDomicilio.getText().length() >= 70) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDomicilioKeyTyped

    private void txtCuilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCuilFocusLost

        
    }//GEN-LAST:event_txtCuilFocusLost

    private void txtBusquedaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBusquedaCaretUpdate
        CargaTabla(consultaProveedor(txtBusqueda.getText().toUpperCase()));
    }//GEN-LAST:event_txtBusquedaCaretUpdate

    private void menuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarActionPerformed
        int i = tblProveedores.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "seleccione una fila");
        } else {
            int dialogresult = JOptionPane.showConfirmDialog(null, "desea elimina la marca");
            if (dialogresult == JOptionPane.YES_OPTION) {
                Proveedor aux;
                String cuil = tblProveedores.getValueAt(i, 1).toString();
                aux = (Proveedor) unaEmpresa.getProveedores().get(cuil);
                try {
                    unaEmpresa.eliminarProveedor(cuil);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_menuEliminarActionPerformed

    private void menuModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModificarActionPerformed
        txtCuil.setEnabled(false);
        int i = tblProveedores.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "seleccione una fila");
        } else {
            Proveedor aux;
            String cuil = tblProveedores.getValueAt(i, 1).toString();
            aux = (Proveedor) unaEmpresa.getProveedores().get(cuil);
            txtCuil.setText(aux.getCUITPro());
            txtTelefono.setText(aux.getDomPro());
            txtRazonSocial.setText(aux.getRazonSocial());
            txtDomicilio.setText(aux.getDomPro());
            txtSaldo.setText(String.valueOf(aux.getSaldo()));
        }
    }//GEN-LAST:event_menuModificarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardarCerPro1;
    private javax.swing.JComboBox cmbCriterioProveedor;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JLabel lblCriterioBusqueda;
    private javax.swing.JLabel lblCuil;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblUsuarioActual2;
    private javax.swing.JMenuItem menuEliminar;
    private javax.swing.JMenuItem menuModificar;
    private javax.swing.JTable tblProveedores;
    private javax.swing.JTextPane txtBusqueda;
    private javax.swing.JTextField txtCuil;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
    public void CargaTabla(Map proveedores) {
        DefaultTableModel modelo = (DefaultTableModel) tblProveedores.getModel();
        Collection lista;
        int filas = tblProveedores.getRowCount();
        for (int i = 0; filas > i; i++)
            modelo.removeRow(0);
        lista = proveedores.values();
        if (!lista.isEmpty()) {
            int i = 0;
            for (Object unObj : lista) {
                Proveedor unPro = (Proveedor) unObj;
                modelo.addRow(new Object[] { (unPro.getRazonSocial()), (unPro.getCUITPro()) });
            }
        }
    }

    public void limpiar() {
        txtCuil.setText("");
        txtTelefono.setText("");
        txtRazonSocial.setText("");
        txtSaldo.setText("");
        txtDomicilio.setText("");
    }

    @Override
    public void update(Observable observable, Object object) {
        CargaTabla(((Empresa) observable).getProveedores());

    }

    public Map consultaProveedor(String consulta) {
        int i = cmbCriterioProveedor.getSelectedIndex();
        Map retorno = new HashMap();
        Proveedor aux = null;
        if(consulta.equals(""))
            return unaEmpresa.getProveedores();
        for (Object unProveedor : unaEmpresa.getProveedores().values().toArray()) {
            aux = (Proveedor) unProveedor;
            if ((i == 0) &&
                (aux.getCUITPro().toUpperCase().contains(consulta) || aux.getRazonSocial().toUpperCase().contains(consulta) ||
                 aux.getDomPro().toUpperCase().contains(consulta) || aux.getDomPro().toUpperCase().contains(consulta))) {
                retorno.put(aux.getCUITPro(), aux);
            }
            if ((i == 1) && (aux.getCUITPro().toUpperCase().contains(consulta))) {
                retorno.put(aux.getCUITPro(), aux);
            }
            if ((i == 2) && (aux.getRazonSocial().toUpperCase().contains(consulta))) {
                retorno.put(aux.getRazonSocial(), aux);
            }
            if ((i == 3) && (aux.getDomPro().toUpperCase().contains(consulta))) {
                retorno.put(aux.getDomPro(), aux);
            }
        }
        return retorno;
    }

    public static Boolean ValidaCuit(String cuit) {
        Boolean valido = false;
        int factor = 5;
        int[] c = new int[11];
        c[10] = Integer.parseInt(cuit.substring(10));
        int resultado = 0;

        for (int i = 0; i < 10; i++) {
            // se toma el valor de cada cifra
            c[i] = Integer.parseInt(Character.toString(cuit.charAt(i)));
            // se suma al resultado el producto de la cifra por el factor que
            // corresponde resultado = resultado + c[i]* factor;
            resultado = resultado + c[i] * factor;
            // se actualiza el valor del factor
            factor = (factor == 2) ? 7 : factor - 1;
        }
        // se obtiene el valor calculado a comparar
        int control = (11 - (resultado % 11)) % 11;
        // Si la cifra de control es igual al valor calculado
        if (control == c[10]) {
            valido = true;
        } else {
            valido = false;
        }
        return valido;
    }
    
    private void reloj() {
        javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent ae) {
                lblFecha1.setText(Calendar.getInstance().getTime().toLocaleString());
            }
        });
        timer.start();
    }
    


}

