
package Interfaz;

import java.awt.Component;
import java.awt.Container;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;

import java.util.Calendar;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Map;

import java.util.Observable;

import java.util.Observer;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import project1.Articulo;
import project1.Caja;
import project1.Compra;
import project1.Empleado;
import project1.Empresa;
import project1.PagoCompra;
import project1.Pago;
import project1.Proveedor;
import project1.TipoPago;
import project1.Venta;

/**
 *
 * @author Adrian
 */
public class GuiPago extends javax.swing.JDialog implements Observer {

    Empresa unaEmpresa;
    boolean esCompra;
    int kill = 0;
    Double Total;
    Boolean modificar = false;
    int nroFila;

    Empleado unEmpleado = GuiVenta.unEmpleado;
    Empleado unUsuario = GuiIngresar.getUsuarioActual();
    Calendar fechaVenta = GuiVenta.fechaVenta;
    String nombreCliente = GuiVenta.nombreCliente;
    String domCliente = GuiVenta.domCliente;
    String nroDocCliente = GuiVenta.nroDocCliente;
    DefaultTableModel modeloVenta = GuiVenta.modelo;
    Calendar fechaCompra = GuiCompras.fechaCompra;
    Proveedor unPro = GuiCompras.unProveedor;
    DefaultTableModel modeloCompra = GuiCompras.modelo;
    private Collection pagos;
    //private Map pagosVenta;

    /** Creates new form NewJDialog3 */
    public GuiPago(javax.swing.JDialog parent, boolean modal, Empresa unaEmpresa, boolean esCompra, Double total) {
        super(parent, modal);
        initComponents();
        this.unaEmpresa = unaEmpresa;
        this.esCompra = esCompra;
        this.Total = total;
        cmbFormaPago1.setModel(new javax.swing.DefaultComboBoxModel(unaEmpresa.getTiposPagos().values().toArray()));
        pagos = new LinkedList();
        //pagosVenta = new HashMap();
        reloj();
        lblUsuarioActual2.setText(GuiIngresar.getUsuario());
        componentes();
        txtFP.requestFocus();
        txtFP.setText(String.valueOf(total));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuEliminar = new javax.swing.JMenuItem();
        menuModificar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnCancelarFormaPago = new javax.swing.JButton();
        btnGuardarFormaPago = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblCBU = new javax.swing.JLabel();
        txtCBU = new javax.swing.JTextField();
        lblNroDoc = new javax.swing.JLabel();
        txtNumeroDoc = new javax.swing.JTextField();
        lblTitular = new javax.swing.JLabel();
        txtTitular = new javax.swing.JTextField();
        lblNroCuenta = new javax.swing.JLabel();
        txtNroCuenta = new javax.swing.JTextField();
        lblNombreBanco = new javax.swing.JLabel();
        txtNombreBanco = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        cmbFormaPago1 = new javax.swing.JComboBox();
        lblFormaPago1 = new javax.swing.JLabel();
        lblFormaPago3 = new javax.swing.JLabel();
        txtPorc1 = new java.awt.TextField();
        lblFormaPago4 = new javax.swing.JLabel();
        txtFP = new java.awt.TextField();
        btnAgregarMarca = new javax.swing.JButton();
        btnAgregarForma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTipoPago = new javax.swing.JTable();
        lblTotalesPorc = new javax.swing.JLabel();
        lblTotales = new javax.swing.JLabel();
        lblTotalesMonto = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblUsuarioActual2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        menuEliminar.setText("Eliminar");
        menuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuEliminar);

        menuModificar.setText("jMenuItem1");
        menuModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuModificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pago");

        jPanel1.setLayout(null);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnCancelarFormaPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1404956598_Delete.png"))); // NOI18N
        btnCancelarFormaPago.setText("Cancelar");
        btnCancelarFormaPago.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnGuardarFormaPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1404955973_Save.png"))); // NOI18N
        btnGuardarFormaPago.setText("Guardar");
        btnGuardarFormaPago.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGuardarFormaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarFormaPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnGuardarFormaPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                .addComponent(btnCancelarFormaPago)
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnCancelarFormaPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarFormaPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(40, 380, 580, 41);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Parametros"));

        lblCBU.setText("CBU");

        lblNroDoc.setText("Numero Doc");

        txtNumeroDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroDocKeyTyped(evt);
            }
        });

        lblTitular.setText("Titular");

        lblNroCuenta.setText("Nro Cuenta");

        lblNombreBanco.setText("NombreBanco");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNroDoc)
                            .addComponent(lblCBU))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblTitular)
                        .addGap(46, 46, 46)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCBU, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(txtNumeroDoc)
                    .addComponent(txtTitular))
                .addGap(61, 61, 61)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNroCuenta)
                    .addComponent(lblNombreBanco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNroCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(txtNombreBanco))
                .addGap(87, 87, 87))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNroCuenta)
                        .addComponent(txtNroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNroDoc)
                        .addComponent(txtNumeroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCBU)
                    .addComponent(txtCBU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreBanco)
                    .addComponent(txtNombreBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitular)
                    .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 250, 680, 130);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Forma de Pago"));

        cmbFormaPago1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbFormaPago1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbFormaPago1MouseExited(evt);
            }
        });
        cmbFormaPago1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFormaPago1ItemStateChanged(evt);
            }
        });
        cmbFormaPago1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFormaPago1ActionPerformed(evt);
            }
        });
        cmbFormaPago1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbFormaPago1FocusLost(evt);
            }
        });

        lblFormaPago1.setText("Forma de Pago");

        lblFormaPago3.setText("Procentaje");

        txtPorc1.setText("100.0");
        txtPorc1.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtPorc1TextValueChanged(evt);
            }
        });
        txtPorc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorc1ActionPerformed(evt);
            }
        });
        txtPorc1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPorc1FocusLost(evt);
            }
        });
        txtPorc1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPorc1KeyTyped(evt);
            }
        });

        lblFormaPago4.setText("Monto");

        txtFP.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtFPTextValueChanged(evt);
            }
        });
        txtFP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFPFocusLost(evt);
            }
        });
        txtFP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFPKeyTyped(evt);
            }
        });

        btnAgregarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1409705665_add.png"))); // NOI18N
        btnAgregarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMarcaActionPerformed(evt);
            }
        });

        btnAgregarForma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1409705665_add.png"))); // NOI18N
        btnAgregarForma.setText("Agregar");
        btnAgregarForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFormaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFormaPago1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cmbFormaPago1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFormaPago3)
                    .addComponent(txtPorc1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblFormaPago4))
                    .addComponent(txtFP, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnAgregarForma, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblFormaPago4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFormaPago3)
                            .addComponent(lblFormaPago1))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btnAgregarForma))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addComponent(txtPorc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAgregarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbFormaPago1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(48, 48, 48))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 160, 680, 90);

        tblTipoPago.setAutoCreateRowSorter(true);
        tblTipoPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblTipoPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo de Pago", "Monto", "Porcentaje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTipoPago.setOpaque(false);
        tblTipoPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTipoPagoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTipoPago);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 680, 110);

        lblTotalesPorc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotalesPorc.setText("0.0");
        lblTotalesPorc.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Porcentaje"));
        jPanel1.add(lblTotalesPorc);
        lblTotalesPorc.setBounds(450, 110, 110, 30);

        lblTotales.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotales.setText("Totales");
        jPanel1.add(lblTotales);
        lblTotales.setBounds(74, 120, 80, 22);

        lblTotalesMonto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotalesMonto.setText("0.0");
        lblTotalesMonto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Monto"));
        jPanel1.add(lblTotalesMonto);
        lblTotalesMonto.setBounds(230, 110, 90, 30);

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel15.setText("Usuario: ");

        lblUsuarioActual2.setText("label");

        jLabel16.setText("fecha:");

        lblFecha.setText("Usuario: ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarioActual2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha)
                .addGap(114, 114, 114))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel16)
                .addComponent(lblFecha)
                .addComponent(jLabel15)
                .addComponent(lblUsuarioActual2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }//GEN-END:initComponents
//GEN-FIRST:event_menuEliminarActionPerformed
    private void btnGuardarFormaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarFormaPagoActionPerformed//GEN-LAST:event_menuEliminarActionPerformed
        if (lblTotalesPorc.getText().equals("100.0")) {//GEN-FIRST:event_btnGuardarFormaPagoActionPerformed
            DefaultTableModel modeloTipo = (DefaultTableModel) tblTipoPago.getModel();
            int filasTipo = modeloTipo.getRowCount();
            try {
                Articulo aux;
                if (esCompra) {
                    int compra = unaEmpresa.agregarCompra(unPro, unUsuario, Total, fechaCompra);
                    Compra unaCompra = (Compra) (unaEmpresa.getCompras().get(compra));
                    int filas = modeloCompra.getRowCount();
                    for (int i = 0; filas > i; i++) {
                        unaCompra.agregarDetalleCompra(Integer.parseInt(modeloCompra.getValueAt(i, 4).toString()),
                                                       Double.parseDouble(modeloCompra.getValueAt(i, 5).toString()),
                                                       (Articulo) unaEmpresa.getArticulos().get(modeloCompra.getValueAt(i, 0)));
                        aux = (Articulo) unaEmpresa.getArticulos().get(modeloCompra.getValueAt(i, 0));
                        aux.setStock(aux.getStock() + Integer.parseInt(modeloCompra.getValueAt(i, 4).toString()));

                    }

                    unaCompra.setPagosCompras(pagos);
                    JOptionPane.showMessageDialog(null, "La compra se cargo con exito");
                    this.dispose();
                } else {
                    int venta = unaEmpresa.agregarVenta(unEmpleado, unUsuario, Total, fechaVenta, nombreCliente, domCliente, nroDocCliente);
                    Venta unaVenta = (Venta) (unaEmpresa.getVentas().get(venta));
                    int filas = modeloVenta.getRowCount();
                    for (int i = 0; filas > i; i++) {
                        unaVenta.agregarDetalleVenta(Integer.parseInt(modeloVenta.getValueAt(i, 4).toString()), Double.parseDouble(modeloVenta.getValueAt(i, 5).toString()),
                                                     (Articulo) unaEmpresa.getArticulos().get(modeloVenta.getValueAt(i, 0)));
                        aux = (Articulo) unaEmpresa.getArticulos().get(modeloVenta.getValueAt(i, 0));
                        aux.setStock(aux.getStock() - Integer.parseInt(modeloVenta.getValueAt(i, 4).toString()));
                    }
                    unaVenta.setPagosVentas(pagos);
                    Caja unaCaja = codCaja();
                    unaCaja.agregarMovimientoCaja(unaVenta);
                    JOptionPane.showMessageDialog(null, "La venta se cargo con exito");
                    this.dispose();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else
            JOptionPane.showMessageDialog(null, "todabia queda saldo");
    }//GEN-LAST:event_btnGuardarFormaPagoActionPerformed

    private void txtNumeroDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroDocKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.')) {
            evt.consume();
        }
        if (txtNumeroDoc.getText().length() >= 13) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroDocKeyTyped

    private void cmbFormaPago1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbFormaPago1MouseClicked

    }//GEN-LAST:event_cmbFormaPago1MouseClicked

    private void cmbFormaPago1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbFormaPago1MouseExited

    }//GEN-LAST:event_cmbFormaPago1MouseExited

    private void cmbFormaPago1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFormaPago1ItemStateChanged

    }//GEN-LAST:event_cmbFormaPago1ItemStateChanged

    private void cmbFormaPago1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFormaPago1ActionPerformed
        componentes();
    }//GEN-LAST:event_cmbFormaPago1ActionPerformed

    private void cmbFormaPago1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbFormaPago1FocusLost

    }//GEN-LAST:event_cmbFormaPago1FocusLost

    private void txtPorc1TextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtPorc1TextValueChanged

    }//GEN-LAST:event_txtPorc1TextValueChanged

    private void txtPorc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorc1ActionPerformed

    private void txtPorc1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPorc1FocusLost
        double j = (Double.parseDouble(txtPorc1.getText()));
        if (j > (100.0 - Double.parseDouble(lblTotalesPorc.getText()))) {
            txtPorc1.setText(String.valueOf(100.0 - Double.parseDouble(lblTotalesPorc.getText())));
        }
        if (!txtPorc1.getText().equals("")) {
            int k = txtPorc1.getCaretPosition();
            txtFP.setText(String.valueOf(Total * Double.parseDouble(txtPorc1.getText()) / 100));
            txtPorc1.setCaretPosition(k);
        }
    }//GEN-LAST:event_txtPorc1FocusLost

    private void txtPorc1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorc1KeyTyped
        char c = evt.getKeyChar();
        double j;
        if (txtPorc1.getText().equals("")) {
            txtPorc1.setText(".0");
        }
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.')) {
            evt.consume();
        } else {
            kill = 0;
        }
        if (c == '.' && txtPorc1.getText().contains(".")) {
            evt.consume();
            int i = txtPorc1.getText().indexOf(".");
            txtPorc1.setCaretPosition(i + 1);
        }
    }//GEN-LAST:event_txtPorc1KeyTyped

    private void txtFPTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtFPTextValueChanged

    }//GEN-LAST:event_txtFPTextValueChanged

    private void txtFPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPFocusLost
        double j = (Double.parseDouble(txtFP.getText()));
        if (j > (Total - Double.parseDouble(lblTotalesMonto.getText()))) {
            txtFP.setText(String.valueOf(Total - Double.parseDouble(lblTotalesMonto.getText())));
        }
        if (!txtFP.getText().equals("")) {
            int i = txtFP.getCaretPosition();
            txtPorc1.setText(String.valueOf(100 * Double.parseDouble(txtFP.getText()) / Total));
            txtFP.setCaretPosition(i);
        }
    }//GEN-LAST:event_txtFPFocusLost

    private void txtFPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFPKeyTyped
        char c = evt.getKeyChar();
        double j;
        if (txtFP.getText().equals("")) {
            txtFP.setText(".0");
        }
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.')) {
            evt.consume();
        } else {
            kill = 0;
        }
        if (c == '.' && txtFP.getText().contains(".")) {
            evt.consume();
            int i = txtPorc1.getText().indexOf(".");
            txtPorc1.setCaretPosition(i + 1);
        }
        if (txtFP.getText().length() >= 7) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFPKeyTyped

    private void btnAgregarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMarcaActionPerformed
        GuiTiposPagos vTipoPago = new GuiTiposPagos(new javax.swing.JDialog(), true, unaEmpresa);
        vTipoPago.setVisible(true);
        DefaultTableModel modelo = (DefaultTableModel) tblTipoPago.getModel();
        actualizar(modelo);
    }//GEN-LAST:event_btnAgregarMarcaActionPerformed

    private void btnAgregarFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFormaActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblTipoPago.getModel();
        Boolean entro = false;
        TipoPago aux = (TipoPago) cmbFormaPago1.getSelectedItem();
        DefaultComboBoxModel modeloCmb = new DefaultComboBoxModel();
        modelo.addRow(new Object[] { aux.toString(), txtFP.getText(), txtPorc1.getText() });
        Pago unPago;
        unPago =
            new Pago((TipoPago) cmbFormaPago1.getSelectedItem(), Double.parseDouble(txtFP.getText()), txtCBU.getText(), txtNombreBanco.getText(), txtNroCuenta.getText(),
                     txtNumeroDoc.getText(), txtTitular.getText());
        pagos.add(unPago);

        Double j = 0.0;
        Double h = 0.0;
        tblTipoPago.setModel(modelo);
        int filas = tblTipoPago.getRowCount();
        for (int i = 0; filas > i; i++) {
            j = j + Double.parseDouble(modelo.getValueAt(i, 1).toString());
            h = h + Double.parseDouble(modelo.getValueAt(i, 2).toString());
        }
        lblTotalesMonto.setText(String.valueOf(j));
        lblTotalesPorc.setText(String.valueOf(h));
        actualizar(modelo);
        if (lblTotalesPorc.getText().equals("100.0")) {
            Component[] components = jPanel5.getComponents();
            for (int i = 0; i < components.length; i++) {
                components[i].setEnabled(false);
                if (components[i] instanceof Container) {
                    components[i].setEnabled(false);
                }
            }
        }
    }//GEN-LAST:event_btnAgregarFormaActionPerformed

    private void tblTipoPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTipoPagoMouseClicked
        if ((evt.getModifiers() & InputEvent.BUTTON3_MASK) == InputEvent.BUTTON3_MASK) {
            jPopupMenu1.setVisible(true);
        }
    }//GEN-LAST:event_tblTipoPagoMouseClicked

    private void txtCBUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCBUKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            kill = 0;
        }
        if (txtFP.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCBUKeyTyped

    private void txtNroCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroCuentaKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            kill = 0;
        }
        if (txtFP.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNroCuentaKeyTyped

    private void menuEliminarActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_menuEliminarActionPerformed
        int i = tblTipoPago.getSelectedRow();
        Double j = 0.0;
        Double h = 0.0;
        String elemento;
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "seleccione una fila");
        } else {
            DefaultTableModel modelo = (DefaultTableModel) tblTipoPago.getModel();
            for (Iterator iter = pagos.iterator(); iter.hasNext();) {
                if (((PagoCompra) iter.next()).getUnTipoPago().getNombre() == modelo.getValueAt(i, 0)) {
                    pagos.remove(iter);
                }
            }
            elemento = String.valueOf(modelo.getValueAt(nroFila, 0));
            modelo.removeRow(nroFila);
            int filas = tblTipoPago.getRowCount();
            for (int l = 0; filas > i; i++) {
                j = j + Double.parseDouble(modelo.getValueAt(l, 1).toString());
                h = h + Double.parseDouble(modelo.getValueAt(l, 2).toString());
            }

            lblTotalesMonto.setText(String.valueOf(j));
            lblTotalesPorc.setText(String.valueOf(h));

        }
    } //GEN-LAST:event_menuEliminarActionPerformed

    private void menuModificarActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_menuModificarActionPerformed
        nroFila = tblTipoPago.getSelectedRow();
        Double j = 0.0;
        Double h = 0.0;
        String elemento;
        if (nroFila == -1) {
            JOptionPane.showMessageDialog(null, "seleccione una fila");
        } else {
            DefaultTableModel modelo = (DefaultTableModel) tblTipoPago.getModel();
            elemento = String.valueOf(modelo.getValueAt(nroFila, 0));
            modelo.removeRow(nroFila);
            int filas = tblTipoPago.getRowCount();
            for (int i = 0; filas > i; i++) {
                j = j + Double.parseDouble(modelo.getValueAt(i, 1).toString());
                h = h + Double.parseDouble(modelo.getValueAt(i, 2).toString());
            }
            lblTotalesMonto.setText(String.valueOf(j));
            lblTotalesPorc.setText(String.valueOf(h));

            for (Iterator iter = pagos.iterator(); iter.hasNext();) {
                PagoCompra unP = (PagoCompra) iter;
                if (unP.getUnTipoPago().getNombre().equals(elemento)) {
                    txtCBU.setText(unP.getCBU());
                    cmbFormaPago1.addItem(unP.getUnTipoPago());
                    cmbFormaPago1.setSelectedItem(unP.getUnTipoPago());
                    txtNombreBanco.setText(unP.getNombreBanco());
                    txtTitular.setText(unP.getTitular());
                    txtNumeroDoc.setText(unP.getNumeroDocumento());
                    txtNroCuenta.setText(unP.getNumeroCuenta());
                    txtFP.setText(String.valueOf(unP.getMonto()));
                    pagos.remove(iter);
                }
            }

        }
        Component[] components = jPanel5.getComponents();
        for (int i = 0; i < components.length; i++) {
            components[i].setEnabled(true);
            if (components[i] instanceof Container) {
                components[i].setEnabled(true);
            }
        }
    } //GEN-LAST:event_menuModificarActionPerformed

    private void txtNombreBancoKeyTyped(java.awt.event.KeyEvent evt) { //GEN-FIRST:event_txtNombreBancoKeyTyped
        if (txtNumeroDoc.getText().length() >= 30) {
            evt.consume();
        }
    } //GEN-LAST:event_txtNombreBancoKeyTyped

    private void txtTitularKeyTyped(java.awt.event.KeyEvent evt) { //GEN-FIRST:event_txtTitularKeyTyped
        if (txtNumeroDoc.getText().length() >= 30) {
            evt.consume();
        }
    } //GEN-LAST:event_txtTitularKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GuiPago dialog = new GuiPago(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarForma;
    private javax.swing.JButton btnAgregarMarca;
    private javax.swing.JButton btnCancelarFormaPago;
    private javax.swing.JButton btnGuardarFormaPago;
    private javax.swing.JComboBox cmbFormaPago1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCBU;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFormaPago1;
    private javax.swing.JLabel lblFormaPago3;
    private javax.swing.JLabel lblFormaPago4;
    private javax.swing.JLabel lblNombreBanco;
    private javax.swing.JLabel lblNroCuenta;
    private javax.swing.JLabel lblNroDoc;
    private javax.swing.JLabel lblTitular;
    private javax.swing.JLabel lblTotales;
    private javax.swing.JLabel lblTotalesMonto;
    private javax.swing.JLabel lblTotalesPorc;
    private javax.swing.JLabel lblUsuarioActual2;
    private javax.swing.JMenuItem menuEliminar;
    private javax.swing.JMenuItem menuModificar;
    private javax.swing.JTable tblTipoPago;
    private javax.swing.JTextField txtCBU;
    private java.awt.TextField txtFP;
    private javax.swing.JTextField txtNombreBanco;
    private javax.swing.JTextField txtNroCuenta;
    private javax.swing.JTextField txtNumeroDoc;
    private java.awt.TextField txtPorc1;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables
    public void componentes() {
        Boolean[] permisos;
        Component[] components = jPanel4.getComponents();
        for (int i = 0; i < components.length; i++) {
            components[i].setVisible(false);
            if (components[i] instanceof Container) {
                components[i].setVisible(false);
            }
        }
        TipoPago aux = (TipoPago) cmbFormaPago1.getSelectedItem();
        permisos = aux.getParametros();
        if (permisos[0]) {
            lblCBU.setVisible(true);
            txtCBU.setVisible(true);
        }
        if (permisos[1]) {
            lblNombreBanco.setVisible(true);
            txtNombreBanco.setVisible(true);

        }
        if (permisos[2]) {
            lblNroCuenta.setVisible(true);
            txtNroCuenta.setVisible(true);
        }
        if (permisos[3]) {
            lblNroDoc.setVisible(true);
            txtNumeroDoc.setVisible(true);
        }
        if (permisos[5]) {
            lblTitular.setVisible(true);
            txtTitular.setVisible(true);
        }

    }


    public Caja codCaja() {
        Caja codCaja = null;
        for (Caja unaCaja : unaEmpresa.getCajas().values()) {
            if (unaCaja.isCajaAbierta()) {
                codCaja = unaCaja;
            }
        }
        return codCaja;
    }

    @Override
    public void update(Observable observable, Object object) {
        DefaultTableModel modelo = (DefaultTableModel) tblTipoPago.getModel();
        actualizar(modelo);
    }

    private void reloj() {
        javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent ae) {
                lblFecha.setText(Calendar.getInstance().getTime().toLocaleString());
            }
        });
        timer.start();
    }

    public void actualizar(DefaultTableModel modelo) {
        int filas = tblTipoPago.getRowCount();
        Boolean entro = false;
        DefaultComboBoxModel modeloCmb = new DefaultComboBoxModel();
        for (TipoPago tipo : unaEmpresa.getTiposPagos().values()) {
            entro = false;
            for (int i = 0; filas > i; i++) {
                if (tipo.getNombre().equals(String.valueOf(modelo.getValueAt(i, 0)))) {
                    entro = true;
                }
            }
            if (entro == false) {
                modeloCmb.addElement(tipo);
            }
        }
        cmbFormaPago1.setModel(modeloCmb);
    }
}
