
package Interfaz;

import java.awt.Toolkit;

import java.util.Calendar;
import java.util.Collection;

import javax.swing.JOptionPane;

import project1.Empresa;
import project1.Rol;

/**
 *
 * @author polaco
 */
public class GuiRol extends javax.swing.JFrame {
    Empresa unaEmpresa;
    int categoria = 0;

    /** Creates new form GuiRol */
    public GuiRol(Empresa unaEmpresa) {
        this.unaEmpresa = unaEmpresa;
        initComponents();
        reloj();
        lblUsuarioActual1.setText(GuiIngresar.getUsuario());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbNombre = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        ckbArticulos = new javax.swing.JCheckBox();
        ckbCompra = new javax.swing.JCheckBox();
        ckbVenta = new javax.swing.JCheckBox();
        ckbSeguridad = new javax.swing.JCheckBox();
        ckbEmpleado = new javax.swing.JCheckBox();
        ckbCaja = new javax.swing.JCheckBox();
        ckbProveedores = new javax.swing.JCheckBox();
        ckbParametros = new javax.swing.JCheckBox();
        ckbBackup = new javax.swing.JCheckBox();
        ckbAuditorias = new javax.swing.JCheckBox();
        ckbEstado = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGuardarCerrar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblUsuarioActual1 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Roles");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/iconos/iconoprograma.png")));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Nombre del Rol");

        cmbNombre.setEditable(true);
        cmbNombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNombreItemStateChanged(evt);
            }
        });
        cmbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNombreActionPerformed(evt);
            }
        });
        cmbNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmbNombreKeyTyped(evt);
            }
        });

        ckbArticulos.setText("Articulos");
        ckbArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbArticulosActionPerformed(evt);
            }
        });

        ckbCompra.setText("Compra");
        ckbCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbCompraActionPerformed(evt);
            }
        });

        ckbVenta.setText("Venta");
        ckbVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbVentaActionPerformed(evt);
            }
        });

        ckbSeguridad.setText("Seguridad");
        ckbSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbSeguridadActionPerformed(evt);
            }
        });

        ckbEmpleado.setText("Empleado");
        ckbEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbEmpleadoActionPerformed(evt);
            }
        });

        ckbCaja.setText("Caja");
        ckbCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbCajaActionPerformed(evt);
            }
        });

        ckbProveedores.setText("Proveedores");
        ckbProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbProveedoresActionPerformed(evt);
            }
        });

        ckbParametros.setText("Parametros");

        ckbBackup.setText("Back Up");
        ckbBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbBackupActionPerformed(evt);
            }
        });

        ckbAuditorias.setText("Auditorias");
        ckbAuditorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbAuditoriasActionPerformed(evt);
            }
        });

        ckbEstado.setText("habilitar");
        ckbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbArticulos)
                    .addComponent(ckbCompra)
                    .addComponent(ckbVenta)
                    .addComponent(ckbSeguridad)
                    .addComponent(ckbEmpleado)
                    .addComponent(ckbCaja)
                    .addComponent(ckbProveedores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbParametros)
                    .addComponent(ckbBackup)
                    .addComponent(ckbAuditorias))
                .addGap(66, 66, 66))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(ckbEstado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbArticulos)
                    .addComponent(ckbParametros))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbCompra)
                    .addComponent(ckbAuditorias))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbVenta)
                    .addComponent(ckbBackup))
                .addGap(18, 18, 18)
                .addComponent(ckbSeguridad)
                .addGap(18, 18, 18)
                .addComponent(ckbEmpleado)
                .addGap(18, 18, 18)
                .addComponent(ckbCaja)
                .addGap(18, 18, 18)
                .addComponent(ckbProveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(ckbEstado)
                .addContainerGap())
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1404956598_Delete.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardarCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1404955973_Save.png"))); // NOI18N
        btnGuardarCerrar.setText("Guardar");
        btnGuardarCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGuardarCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardarCerrar)
                .addGap(70, 70, 70)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardarCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel13.setText("Usuario: ");

        lblUsuarioActual1.setText("label");

        lblFecha.setText("Usuario: ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarioActual1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(lblFecha)
                .addGap(60, 60, 60))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblFecha)
                .addComponent(jLabel13)
                .addComponent(lblUsuarioActual1))
        );

        jLabel14.setText("fecha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(419, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }//GEN-END:initComponents

    private void ckbArticulosActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_ckbArticulosActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_ckbArticulosActionPerformed

    private void ckbCompraActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_ckbCompraActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_ckbCompraActionPerformed

    private void ckbVentaActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_ckbVentaActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_ckbVentaActionPerformed

    private void ckbSeguridadActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_ckbSeguridadActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_ckbSeguridadActionPerformed

    private void ckbEmpleadoActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_ckbEmpleadoActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_ckbEmpleadoActionPerformed

    private void ckbCajaActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_ckbCajaActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_ckbCajaActionPerformed

    private void ckbProveedoresActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_ckbProveedoresActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_ckbProveedoresActionPerformed

    private void ckbTurnosActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_ckbTurnosActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_ckbTurnosActionPerformed

    private void ckbBackupActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_ckbBackupActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_ckbBackupActionPerformed

    private void ckbAuditoriasActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_ckbAuditoriasActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_ckbAuditoriasActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_btnCancelarMouseClicked

    } //GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnCancelarActionPerformed
        ckbEmpleado.setSelected(false);
        ckbSeguridad.setSelected(false);
        ckbVenta.setSelected(false);
        ckbArticulos.setSelected(false);
        ckbAuditorias.setSelected(false);
        ckbBackup.setSelected(false);
        ckbCaja.setSelected(false);
        ckbCompra.setSelected(false);
        ckbProveedores.setSelected(false);
        ckbEstado.setSelected(false);
        ckbParametros.setSelected(false);
        cmbNombre.setEnabled(true);
    } //GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarCerrarActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnGuardarCerrarActionPerformed
        Boolean[] permiso;
        permiso = new Boolean[10];
        Boolean estado = false;
        if (!cmbNombre.getSelectedItem().equals("")) {
            if (ckbEmpleado.isSelected()) {
                permiso[0] = true;
            } else {
                permiso[0] = false;
            }
            if (ckbSeguridad.isSelected()) {
                permiso[1] = true;
            } else {
                permiso[1] = false;
            }
            if (ckbVenta.isSelected()) {
                permiso[2] = true;
            } else {
                permiso[2] = false;
            }
            if (ckbArticulos.isSelected()) {
                permiso[3] = true;
            } else {
                permiso[3] = false;
            }
            if (ckbAuditorias.isSelected()) {
                permiso[4] = true;
            } else {
                permiso[4] = false;
            }
            if (ckbBackup.isSelected()) {
                permiso[5] = true;
            } else {
                permiso[5] = false;
            }
            if (ckbCaja.isSelected()) {
                permiso[6] = true;
            } else {
                permiso[6] = false;
            }
            if (ckbCompra.isSelected()) {
                permiso[7] = true;
            } else {
                permiso[7] = false;
            }
            if (ckbProveedores.isSelected()) {
                permiso[8] = true;
            } else {
                permiso[8] = false;
            }
            if (ckbParametros.isSelected()) {
                permiso[9] = true;
            } else {
                permiso[9] = false;
            }
            if (ckbEstado.isSelected()) {
                estado = true;
            }
            if ((!ckbArticulos.isSelected() && !ckbAuditorias.isSelected() && !ckbBackup.isSelected() && !ckbBackup.isSelected() && !ckbCaja.isSelected() &&
                 !ckbCompra.isSelected() && !ckbEmpleado.isSelected() && !ckbProveedores.isSelected() && !ckbSeguridad.isSelected() && !ckbVenta.isSelected() &&
                 !ckbParametros.isSelected()))
                JOptionPane.showMessageDialog(null, "No selecciono ningun Rol", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            else {
                try {
                    if (cmbNombre.isEnabled()) {
                        unaEmpresa.agregarRol(cmbNombre.getSelectedItem().toString(), permiso, estado);
                        JOptionPane.showMessageDialog(null, "El rol se cargo con exito");
                    } else {
                        unaEmpresa.modificarRol(categoria, cmbNombre.getSelectedItem().toString(), permiso, estado);
                        JOptionPane.showMessageDialog(null, "El rol se modifico con exito");
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        } else
            JOptionPane.showMessageDialog(null, "No ingreso el Nombre del Rol", "Informacion", JOptionPane.INFORMATION_MESSAGE);
    } //GEN-LAST:event_btnGuardarCerrarActionPerformed

    private void ckbEstadoActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_ckbEstadoActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_ckbEstadoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) { //GEN-FIRST:event_formWindowActivated
        actualizarNombre();
    } //GEN-LAST:event_formWindowActivated

    private void cmbNombreItemStateChanged(java.awt.event.ItemEvent evt) { //GEN-FIRST:event_cmbNombreItemStateChanged

    } //GEN-LAST:event_cmbNombreItemStateChanged

    private void cmbNombreActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_cmbNombreActionPerformed
        Collection lista = unaEmpresa.getRoles().values();
        for (Object unObj : lista) {
            Rol unRol = (Rol) unObj;
            if (unRol.getNombre().equals(cmbNombre.getSelectedItem().toString())) {
                cmbNombre.setEnabled(false);
                categoria = unRol.getIdRol();
                if (unRol.getPermiso()[0]) {
                    ckbEmpleado.setSelected(true);
                }
                if (unRol.getPermiso()[1]) {
                    ckbSeguridad.setSelected(true);
                }
                if (unRol.getPermiso()[2]) {
                    ckbVenta.setSelected(true);
                }
                if (unRol.getPermiso()[3]) {
                    ckbArticulos.setSelected(true);
                }
                if (unRol.getPermiso()[4]) {
                    ckbAuditorias.setSelected(true);
                }
                if (unRol.getPermiso()[5]) {
                    ckbBackup.setSelected(true);
                }
                if (unRol.getPermiso()[6]) {
                    ckbCaja.setSelected(true);
                }
                if (unRol.getPermiso()[7]) {
                    ckbCompra.setSelected(true);
                }
                if (unRol.getPermiso()[8]) {
                    ckbProveedores.setSelected(true);
                }
                if (unRol.getPermiso()[9]) {
                    ckbParametros.setSelected(true);
                }
                if (unRol.getEstado()) {
                    ckbEstado.setSelected(true);
                } else {
                    ckbEstado.setSelected(false);
                }
            }
        }
    } //GEN-LAST:event_cmbNombreActionPerformed

    private void cmbNombreKeyTyped(java.awt.event.KeyEvent evt) { //GEN-FIRST:event_cmbNombreKeyTyped

    } //GEN-LAST:event_cmbNombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiRol().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardarCerrar;
    private javax.swing.JCheckBox ckbArticulos;
    private javax.swing.JCheckBox ckbAuditorias;
    private javax.swing.JCheckBox ckbBackup;
    private javax.swing.JCheckBox ckbCaja;
    private javax.swing.JCheckBox ckbCompra;
    private javax.swing.JCheckBox ckbEmpleado;
    private javax.swing.JCheckBox ckbEstado;
    private javax.swing.JCheckBox ckbParametros;
    private javax.swing.JCheckBox ckbProveedores;
    private javax.swing.JCheckBox ckbSeguridad;
    private javax.swing.JCheckBox ckbVenta;
    private javax.swing.JComboBox cmbNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblUsuarioActual1;
    // End of variables declaration//GEN-END:variables

    public void actualizarNombre() {
        cmbNombre.setModel(new javax.swing.DefaultComboBoxModel(unaEmpresa.getRoles().values().toArray()));
    }

    private void reloj() {
        javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent ae) {
                lblFecha.setText(Calendar.getInstance().getTime().toLocaleString());
            }
        });
        timer.start();
    }
}
