
package Interfaz;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import project1.Articulo;
import project1.Categoria;
import project1.Empresa;

/**
 *
 * @author Adrian
 */
public class GuiSeleccionArt extends javax.swing.JDialog {
    Empresa unaEmpresa;
    String unArt;

    /** Creates new form GuiSeleccionArt */
    public GuiSeleccionArt(java.awt.Frame parent, boolean modal, Empresa unaEmpresa, String unArt) {
        super(parent, modal);
        this.unaEmpresa = unaEmpresa;
        initComponents();
        actualizarComboCategoria1();
        actualizarComboMarca();
        CargaTablaArticulos(unaEmpresa.getArticulos());
        actualizarComboMarca();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel1 = new javax.swing.JPanel();
        lblCategoria1 = new javax.swing.JLabel();
        cmbCategoria2 = new javax.swing.JComboBox();
        lblCategoria2 = new javax.swing.JLabel();
        lblCategoria3 = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        cmbMarca = new javax.swing.JComboBox();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cmbSexo = new javax.swing.JComboBox();
        cmbCategoriaFiltro1 = new javax.swing.JComboBox();
        btnBuscar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblArticulos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Consulta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        lblCategoria1.setText("Categoria 1");

        cmbCategoria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoria2ActionPerformed(evt);
            }
        });

        lblCategoria2.setText("Categoria 2");

        lblCategoria3.setText("sexo");

        lblMarca.setText("Marca");

        lblNombre.setText("Nombre");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Caballero", "Dama" }));

        cmbCategoriaFiltro1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCategoriaFiltro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaFiltro1ActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1412652047_search-32.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMarca)
                    .addComponent(lblNombre)
                    .addComponent(lblCategoria2)
                    .addComponent(lblCategoria1)
                    .addComponent(lblCategoria3))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre)
                    .addComponent(cmbMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbCategoria2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbSexo, 0, 193, Short.MAX_VALUE)
                    .addComponent(cmbCategoriaFiltro1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMarca)
                    .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria1)
                    .addComponent(cmbCategoriaFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria2))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria3)
                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(44, 44, 44))
        );

        tblArticulos.setAutoCreateRowSorter(true);
        tblArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo de Barra", "Nombre", "Marca", "Color", "Color2", "Categoria", "Categoria2", "Stock", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblArticulosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblArticulos);
        tblArticulos.getColumnModel().getColumn(0).setHeaderValue("Codigo de Barra");
        tblArticulos.getColumnModel().getColumn(1).setHeaderValue("Nombre");
        tblArticulos.getColumnModel().getColumn(2).setHeaderValue("Marca");
        tblArticulos.getColumnModel().getColumn(3).setHeaderValue("Color");
        tblArticulos.getColumnModel().getColumn(4).setHeaderValue("Color2");
        tblArticulos.getColumnModel().getColumn(5).setHeaderValue("Categoria");
        tblArticulos.getColumnModel().getColumn(6).setHeaderValue("Categoria2");
        tblArticulos.getColumnModel().getColumn(7).setHeaderValue("Stock");
        tblArticulos.getColumnModel().getColumn(8).setHeaderValue("Precio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }//GEN-END:initComponents

    private void cmbCategoria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoria2ActionPerformed
        //actualizarCategoria3();
    }//GEN-LAST:event_cmbCategoria2ActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        if (txtNombre.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void cmbCategoriaFiltro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaFiltro1ActionPerformed
        actualizarCategoria2();
    }//GEN-LAST:event_cmbCategoriaFiltro1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        consultaArticulos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblArticulosMouseClicked
        if (evt.getClickCount() == 2) {
            int i = tblArticulos.getSelectedRow();
            if (i == -1) {
                JOptionPane.showMessageDialog(null, "seleccione una fila");
            } else {
                String nroCodBarra = tblArticulos.getValueAt(i, 0).toString();
                this.setUnArt(nroCodBarra);
                this.dispose();
            }
        }
    }//GEN-LAST:event_tblArticulosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiSeleccionArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiSeleccionArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiSeleccionArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiSeleccionArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GuiSeleccionArt dialog = new GuiSeleccionArt(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox cmbCategoria2;
    private javax.swing.JComboBox cmbCategoriaFiltro1;
    private javax.swing.JComboBox cmbMarca;
    private javax.swing.JComboBox cmbSexo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCategoria1;
    private javax.swing.JLabel lblCategoria2;
    private javax.swing.JLabel lblCategoria3;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tblArticulos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
    public void CargaTablaArticulos(Map articulos) {
        DefaultTableModel modelo = (DefaultTableModel) tblArticulos.getModel();
        limpiarTabla(tblArticulos, modelo);
        Collection lista;
        lista = articulos.values();
        if (!lista.isEmpty()) {
            for (Object unObj : lista) {
                Articulo unArt = (Articulo) unObj;
                Categoria cate = (Categoria) unaEmpresa.getCategorias().get(unArt.getUnaCategoria().getCodPadre());
                modelo.addRow(new Object[] {
                              (unArt.getCodBarra()), (unArt.getNombre()), (unArt.getUnaMarca().getNombreMarca()), (unArt.getColor()), (unArt.getColor2()),
                              (unArt.getUnaCategoria().getCodPadre()), (unArt.getUnaCategoria()), (unArt.getStock()), (unArt.getPrecioVenta())
                });
            }
        }
    }

    private void limpiarTabla(JTable tabla, DefaultTableModel modelo) {
        int filas = tabla.getRowCount();
        for (int i = 0; filas > i; i++)
            modelo.removeRow(0);
    }

    public void actualizarComboCategoria1() {
        Map cargar = new HashMap();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();

        for (Categoria unaCa : unaEmpresa.getCategorias().values()) {
            if (unaCa.getEsPadre() == true)
                modelo.addElement(unaCa);
        }
        cmbCategoriaFiltro1.setModel(modelo);
        cmbCategoriaFiltro1.addItem("Todos");
        cmbCategoriaFiltro1.setSelectedItem("Todos");
    }

    public void actualizarCategoria2() {
        if (!cmbCategoriaFiltro1.getSelectedItem().equals("Todos")) {
            int codCat = ((Categoria) cmbCategoriaFiltro1.getSelectedItem()).getNroCateg();
            Map hijos = new HashMap();
            for (Categoria unaCa : unaEmpresa.getCategorias().values()) {
                if (unaCa.getCodPadre() == codCat) {
                    hijos.put(unaCa.getNroCateg(), unaCa);
                }
            }
            cmbCategoria2.setModel(new javax.swing.DefaultComboBoxModel(hijos.values().toArray()));
        }
        cmbCategoria2.addItem("Todos");
        cmbCategoria2.setSelectedItem("Todos");
    }

    public void actualizarComboMarca() {
        cmbMarca.setModel(new javax.swing.DefaultComboBoxModel(unaEmpresa.getMarcas().values().toArray()));
        cmbMarca.addItem("Todos");
        cmbMarca.setSelectedItem("Todos");
    }

    public Map consultaArticulos() {
        Map retorno = new HashMap();
        Articulo aux = null;

        for (Object unArt : unaEmpresa.getArticulos().values().toArray()) {
            aux = (Articulo) unArt;
            if (aux.getUnaMarca().equals(cmbMarca.getSelectedItem()) || cmbMarca.getSelectedItem().equals("Todos"))
                if (aux.getNombre().toUpperCase().startsWith(txtNombre.getText()) || txtNombre.getText().equals("Todos"))
                    if (cmbCategoriaFiltro1.getSelectedItem().equals("Todos") ||
                        aux.getUnaCategoria().getCodPadre() == (((Categoria) cmbCategoriaFiltro1.getSelectedItem()).getNroCateg()))
                        if (cmbCategoria2.getSelectedItem().equals("Todos") || aux.getUnaCategoria().equals(cmbCategoria2.getSelectedItem()))
                            if (cmbSexo.getSelectedItem().equals("Todos") ||
                                aux.getSexo().toString().toUpperCase().equals(cmbSexo.getSelectedItem().toString().toUpperCase())) {
                                retorno.put(aux.getCodBarra(), aux);
                            }
        }
        CargaTablaArticulos(retorno);
        return retorno;
    }

    public void setUnArt(String unArt) {
        this.unArt = unArt;
    }

    public String getUnArt() {
        return unArt;
    }
}
