
package Interfaz;

import java.awt.Toolkit;
import java.awt.event.InputEvent;

import java.util.Calendar;
import java.util.Collection;
import java.util.Map;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import project1.Empresa;
import project1.TipoPago;

/**
 *
 * @author German
 */
public class GuiTiposPagos1 extends javax.swing.JFrame {
    Empresa unaEmpresa;

    /** Creates new form NewJFrame */
    public GuiTiposPagos1(Empresa unaEmpresa) {
        this.unaEmpresa = unaEmpresa;
        initComponents();
        reloj();
        lblUsuarioActual2.setText(GuiIngresar.getUsuario());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuEliminar = new javax.swing.JMenuItem();
        menuModificar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTipoPago = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        lblNombreTipoPago = new javax.swing.JLabel();
        txtNombreTipoPago = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnGuardarNueTipoPago = new javax.swing.JButton();
        btnCancelarTipoPago = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cbkTitular = new javax.swing.JCheckBox();
        cbkCbu = new javax.swing.JCheckBox();
        cbkTipoCuenta = new javax.swing.JCheckBox();
        cbkNumeroCuenta = new javax.swing.JCheckBox();
        cbkNumeroDocumento = new javax.swing.JCheckBox();
        cbkNombreBanco = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblUsuarioActual2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        jPopupMenu1.setInvoker(lstTipoPago);

        menuEliminar.setText("Eliminar");
        menuEliminar.setName(""); // NOI18N
        menuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuEliminar);
        menuEliminar.getAccessibleContext().setAccessibleParent(jPopupMenu1);

        menuModificar.setText("Modificar");
        menuModificar.setAutoscrolls(true);
        menuModificar.setComponentPopupMenu(jPopupMenu1);
        menuModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuModificarMouseClicked(evt);
            }
        });
        menuModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuModificar);

        jPopupMenu1.getAccessibleContext().setAccessibleParent(lstTipoPago);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tipos de Pago");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/iconos/iconoprograma.png")));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lstTipoPago.setComponentPopupMenu(jPopupMenu1);
        lstTipoPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTipoPagoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstTipoPago);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nuevo Tipo Pago"));

        lblNombreTipoPago.setText("Nombre");

        txtNombreTipoPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreTipoPagoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreTipoPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(txtNombreTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreTipoPago))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnGuardarNueTipoPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1404955973_Save.png"))); // NOI18N
        btnGuardarNueTipoPago.setText("Guardar");
        btnGuardarNueTipoPago.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGuardarNueTipoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNueTipoPagoActionPerformed(evt);
            }
        });

        btnCancelarTipoPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1404956598_Delete.png"))); // NOI18N
        btnCancelarTipoPago.setText("Cancelar");
        btnCancelarTipoPago.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelarTipoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTipoPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardarNueTipoPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarTipoPago)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarNueTipoPago, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btnCancelarTipoPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Parametros del Tipo Pago"));

        cbkTitular.setText("Titular");

        cbkCbu.setText("CBU");

        cbkTipoCuenta.setText("Tipo Cuenta");

        cbkNumeroCuenta.setText("Numero Cuenta");

        cbkNumeroDocumento.setText("Numero Documento");

        cbkNombreBanco.setText("Nombre Banco");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbkTitular)
                    .addComponent(cbkTipoCuenta)
                    .addComponent(cbkNumeroDocumento))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbkNumeroCuenta)
                    .addComponent(cbkNombreBanco)
                    .addComponent(cbkCbu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbkTitular)
                    .addComponent(cbkCbu))
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbkTipoCuenta)
                    .addComponent(cbkNumeroCuenta))
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbkNumeroDocumento)
                    .addComponent(cbkNombreBanco))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel15.setText("Usuario: ");

        lblUsuarioActual2.setText("label");

        jLabel16.setText("fecha:");

        lblFecha.setText("Usuario: ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarioActual2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha)
                .addGap(114, 114, 114))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel16)
                .addComponent(lblFecha)
                .addComponent(jLabel15)
                .addComponent(lblUsuarioActual2))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 235, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }//GEN-END:initComponents

    private void lstTipoPagoMouseClicked(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_lstTipoPagoMouseClicked
        if ((evt.getModifiers() & InputEvent.BUTTON3_MASK) == InputEvent.BUTTON3_MASK) {
            jPopupMenu1.setVisible(true);
        }
    } //GEN-LAST:event_lstTipoPagoMouseClicked

    private void btnGuardarNueTipoPagoActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnGuardarNueTipoPagoActionPerformed
        if (aprobado()) {
            if (!lstTipoPago.isEnabled()) {
                try {
                    unaEmpresa.modificarTipoPago(lstTipoPago.getSelectedValue().toString(), txtNombreTipoPago.getText(), permiso());
                    JOptionPane.showMessageDialog(null, "El tipo de pago se modifico con exito");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
                lstTipoPago.setEnabled(true);

            } else {
                try {
                    unaEmpresa.agregarTipoPago(txtNombreTipoPago.getText(), permiso());
                    JOptionPane.showMessageDialog(null, "El tipo de pago se cargo con exito");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
            cargar(unaEmpresa.getTiposPagos());
            limpiar();
            txtNombreTipoPago.setText("");
        } else
            JOptionPane.showMessageDialog(null, "No ingreso el Nombre o el nombre ya existe", null, JOptionPane.INFORMATION_MESSAGE);

    } //GEN-LAST:event_btnGuardarNueTipoPagoActionPerformed

    private void btnCancelarTipoPagoActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnCancelarTipoPagoActionPerformed
        txtNombreTipoPago.setText("");
        lstTipoPago.setEnabled(true);
    } //GEN-LAST:event_btnCancelarTipoPagoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) { //GEN-FIRST:event_formWindowActivated
        cargar(unaEmpresa.getTiposPagos());
    } //GEN-LAST:event_formWindowActivated

    private void menuModificarMouseClicked(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_menuModificarMouseClicked

    } //GEN-LAST:event_menuModificarMouseClicked

    private void menuModificarActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_menuModificarActionPerformed
        int i = lstTipoPago.getSelectedIndex();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "no selecciono un Tipo Pago");
        } else {
            lstTipoPago.setEnabled(false);
            txtNombreTipoPago.setText(lstTipoPago.getSelectedValue().toString());
            limpiar();
            TipoPago unTipo = unaEmpresa.getTiposPagos().get(txtNombreTipoPago.getText());
            Boolean[] permiso = unTipo.getParametros();
            if (permiso[0])
                cbkCbu.setSelected(true);
            if (permiso[1])
                cbkNombreBanco.setSelected(true);
            if (permiso[2])
                cbkNumeroCuenta.setSelected(true);
            if (permiso[3])
                cbkNumeroDocumento.setSelected(true);
            if (permiso[4])
                cbkTipoCuenta.setSelected(true);
            if (permiso[5])
                cbkTitular.setSelected(true);
        }
    } //GEN-LAST:event_menuModificarActionPerformed

    private void menuEliminarActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_menuEliminarActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_menuEliminarActionPerformed

    private void txtNombreTipoPagoKeyTyped(java.awt.event.KeyEvent evt) { //GEN-FIRST:event_txtNombreTipoPagoKeyTyped
        if (txtNombreTipoPago.getText().length() >= 30) {
            evt.consume();
        }
    } //GEN-LAST:event_txtNombreTipoPagoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiTiposPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiTiposPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiTiposPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiTiposPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiTiposPagos().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarTipoPago;
    private javax.swing.JButton btnGuardarNueTipoPago;
    private javax.swing.JCheckBox cbkCbu;
    private javax.swing.JCheckBox cbkNombreBanco;
    private javax.swing.JCheckBox cbkNumeroCuenta;
    private javax.swing.JCheckBox cbkNumeroDocumento;
    private javax.swing.JCheckBox cbkTipoCuenta;
    private javax.swing.JCheckBox cbkTitular;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombreTipoPago;
    private javax.swing.JLabel lblUsuarioActual2;
    private javax.swing.JList lstTipoPago;
    private javax.swing.JMenuItem menuEliminar;
    private javax.swing.JMenuItem menuModificar;
    private javax.swing.JTextField txtNombreTipoPago;
    // End of variables declaration//GEN-END:variables
    public void cargar(Map tiposPagos) {
        Collection lista;
        lista = tiposPagos.values();
        DefaultListModel modelo = new DefaultListModel();
        if (!lista.isEmpty()) {
            int i = 0;
            for (Object unObj : lista) {
                TipoPago unTipoPago = (TipoPago) unObj;
                modelo.addElement(unTipoPago.getNombre());

            }
            lstTipoPago.setModel(modelo);
        }
    }

    public void limpiar() {
        cbkCbu.setSelected(false);
        cbkNombreBanco.setSelected(false);
        cbkNumeroCuenta.setSelected(false);
        cbkNumeroDocumento.setSelected(false);
        cbkTipoCuenta.setSelected(false);
        cbkTitular.setSelected(false);
    }

    public Boolean[] permiso() {
        Boolean[] permisos = new Boolean[6];
        if (!txtNombreTipoPago.getText().equals("")) {
            if (cbkCbu.isSelected()) {
                permisos[0] = true;
            } else {
                permisos[0] = false;
            }
            if (cbkNombreBanco.isSelected()) {
                permisos[1] = true;
            } else {
                permisos[1] = false;
            }
            if (cbkNumeroCuenta.isSelected()) {
                permisos[2] = true;
            } else {
                permisos[2] = false;
            }
            if (cbkNumeroDocumento.isSelected()) {
                permisos[3] = true;
            } else {
                permisos[3] = false;
            }
            if (cbkTipoCuenta.isSelected()) {
                permisos[4] = true;
            } else {
                permisos[4] = false;
            }
            if (cbkTitular.isSelected()) {
                permisos[5] = true;
            } else {
                permisos[5] = false;
            }
        } else
            JOptionPane.showMessageDialog(null, "no ingreso el nombre");
        return permisos;
    }

    private Boolean aprobado() {
        Boolean existe = true;
        if (!(txtNombreTipoPago.getText().equals(""))) {
            for (TipoPago tipo : unaEmpresa.getTiposPagos().values()) {
                if (tipo.getNombre().equals(txtNombreTipoPago.getText()))
                    existe = false;
            }
        } else
            existe = false;
        return existe;
    }

    private void reloj() {
        javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent ae) {
                lblFecha.setText(Calendar.getInstance().getTime().toLocaleString());
            }
        });
        timer.start();
    }
}
