
package Interfaz;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Map;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import project1.Articulo;
import project1.Empleado;
import project1.Empresa;

/**
 *
 * @author polaco
 */
public class GuiVenta extends javax.swing.JFrame implements Runnable {
    Empresa unaEmpresa;
    Boolean modificar = false;
    int nroFila;
    int stock;
    double total;
    public static Calendar fechaVenta;
    public static String nombreCliente;
    public static String domCliente;
    public static String nroDocCliente;
    public static Empleado unUsuario;
    public static Empleado unEmpleado;
    public static DefaultTableModel modelo;
    Thread hilo;
    int kill = 0;
    Double Total = 0.0;

    /** Creates new form Venta */
    public GuiVenta(Empresa unaEmpresa) {
        this.unaEmpresa = unaEmpresa;
        initComponents();
        hilo = new Thread(this);
        hilo.start();
        lblUsuarioActual.setText(GuiIngresar.getUsuario());
        actualizarComboEmpleado();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPopupMenu1 = new javax.swing.JPopupMenu();
        MenuEliminar = new javax.swing.JMenuItem();
        MenuModificar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblNombreCliente = new javax.swing.JLabel();
        lblNroDocCliente = new javax.swing.JLabel();
        lblDomCliente = new javax.swing.JLabel();
        lblFechaVenta = new javax.swing.JLabel();
        txtFechaVenta = new javax.swing.JFormattedTextField();
        lblEmpleado = new javax.swing.JLabel();
        cmbEmpleado = new javax.swing.JComboBox();
        btnAgregarEmpleado = new javax.swing.JButton();
        txtNomCliente = new javax.swing.JTextField();
        txtDoc = new javax.swing.JTextField();
        txtDom = new javax.swing.JTextField();
        panel1 = new javax.swing.JPanel();
        lblCodBarra = new javax.swing.JLabel();
        txtCodigodeBarra = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnAgregarArticulo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMonto = new java.awt.TextField();
        lblFormaPago4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFormaPago6 = new javax.swing.JLabel();
        txtMonto1 = new java.awt.TextField();
        lblTotal1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtCantidad = new java.awt.TextField();
        lblStock2 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVenta = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnGuardarNueVenta = new javax.swing.JButton();
        btnCancelarVenta = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblUsuarioActual = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        MenuEliminar.setText("Eliminar");
        MenuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MenuEliminar);
        MenuEliminar.getAccessibleContext().setAccessibleParent(jPopupMenu1);

        MenuModificar.setLabel("Modificar");
        MenuModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuModificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MenuModificar);
        MenuModificar.getAccessibleContext().setAccessibleParent(jPopupMenu1);

        jPopupMenu1.getAccessibleContext().setAccessibleParent(tblVenta);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventas");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/iconos/iconoprograma.png")));

        lblNombreCliente.setText("Nombre Cliente*");

        lblNroDocCliente.setText("Nro de Documento*");

        lblDomCliente.setText("Domicilio");

        lblFechaVenta.setText("Fecha");

        txtFechaVenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtFechaVenta.setEnabled(false);

        lblEmpleado.setText("Empleado");

        cmbEmpleado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAgregarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1409705665_add.png"))); // NOI18N
        btnAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEmpleadoActionPerformed(evt);
            }
        });

        txtNomCliente.setNextFocusableComponent(txtDoc);
        txtNomCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomClienteKeyTyped(evt);
            }
        });

        txtDoc.setNextFocusableComponent(txtDom);
        txtDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocKeyTyped(evt);
            }
        });

        txtDom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDomKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCliente)
                    .addComponent(lblNroDocCliente)
                    .addComponent(lblDomCliente))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(264, 264, 264)
                                .addComponent(lblEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDom, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFechaVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEmpleado)
                                .addComponent(cmbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnAgregarEmpleado, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFechaVenta)
                                .addComponent(txtFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNombreCliente)
                                .addComponent(txtNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNroDocCliente)
                            .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDomCliente)
                    .addComponent(txtDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lblCodBarra.setText("Codigo de Barra*");

        txtCodigodeBarra.setNextFocusableComponent(txtCantidad);
        txtCodigodeBarra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigodeBarraFocusLost(evt);
            }
        });
        txtCodigodeBarra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigodeBarraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigodeBarraKeyTyped(evt);
            }
        });

        lblCantidad.setText("Cantidad*");

        lblPrecio.setText("Precio Unitario*");

        txtPrecio.setNextFocusableComponent(btnAgregar);
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1409705665_add.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnAgregarArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1409705665_add.png"))); // NOI18N
        btnAgregarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArticuloActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/delete-icon.png"))); // NOI18N
        btnCancelar.setText("cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblTotal.setBackground(new java.awt.Color(0, 0, 0));
        lblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("Descuento");

        txtMonto.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtMontoTextValueChanged(evt);
            }
        });
        txtMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMontoFocusLost(evt);
            }
        });
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });

        lblFormaPago4.setText("Monto");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Total");

        jLabel3.setText("Descuento");

        lblFormaPago6.setText("Monto");

        txtMonto1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMonto1FocusLost(evt);
            }
        });
        txtMonto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMonto1KeyTyped(evt);
            }
        });

        lblTotal1.setBackground(new java.awt.Color(0, 0, 0));
        lblTotal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblTotal1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Precio C/U");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1412329438_685082-Search-16.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtCantidad.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtCantidadTextValueChanged(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        lblStock2.setText(" ");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(lblCodBarra)
                        .addGap(3, 3, 3)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(txtCodigodeBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btnAgregarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblStock2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(lblCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(268, 268, 268)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(lblPrecio)
                        .addGap(119, 119, 119)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(lblTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFormaPago6)
                                    .addComponent(txtMonto1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(40, 40, 40)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar)
                    .addComponent(btnCancelar))
                .addGap(125, 125, 125)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(49, 49, 49)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFormaPago4))))
                .addGap(95, 95, 95))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblFormaPago6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMonto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGap(25, 25, 25))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(btnCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnAgregarArticulo)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(lblCodBarra)
                                                    .addComponent(txtCodigodeBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel1Layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(lblCantidad))
                                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAgregar)
                                    .addComponent(lblStock2)))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(lblFormaPago4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        tblVenta.setAutoCreateRowSorter(true);
        tblVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo de Barra", "Descripcion", "Talle", "Color", "Cantidad", "Precio", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVenta.setComponentPopupMenu(jPopupMenu1);
        tblVenta.getTableHeader().setReorderingAllowed(false);
        tblVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVentaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVenta);
        tblVenta.getColumnModel().getColumn(0).setPreferredWidth(200);
        tblVenta.getColumnModel().getColumn(0).setHeaderValue("Codigo de Barra");
        tblVenta.getColumnModel().getColumn(1).setPreferredWidth(400);
        tblVenta.getColumnModel().getColumn(1).setHeaderValue("Descripcion");
        tblVenta.getColumnModel().getColumn(2).setPreferredWidth(9);
        tblVenta.getColumnModel().getColumn(2).setHeaderValue("Talle");
        tblVenta.getColumnModel().getColumn(3).setPreferredWidth(9);
        tblVenta.getColumnModel().getColumn(3).setHeaderValue("Color");
        tblVenta.getColumnModel().getColumn(4).setPreferredWidth(9);
        tblVenta.getColumnModel().getColumn(4).setHeaderValue("Cantidad");
        tblVenta.getColumnModel().getColumn(5).setPreferredWidth(9);
        tblVenta.getColumnModel().getColumn(5).setHeaderValue("Precio");
        tblVenta.getColumnModel().getColumn(6).setPreferredWidth(9);
        tblVenta.getColumnModel().getColumn(6).setHeaderValue("Total");

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnGuardarNueVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1405280090_15_Tick_32x32.png"))); // NOI18N
        btnGuardarNueVenta.setText("Aceptar");
        btnGuardarNueVenta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGuardarNueVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarNueVentaMouseClicked(evt);
            }
        });
        btnGuardarNueVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNueVentaActionPerformed(evt);
            }
        });

        btnCancelarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1404956598_Delete.png"))); // NOI18N
        btnCancelarVenta.setText("Cancelar");
        btnCancelarVenta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarVentaMouseClicked(evt);
            }
        });
        btnCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnGuardarNueVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 989, Short.MAX_VALUE)
                .addComponent(btnCancelarVenta)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarNueVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btnCancelarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel11.setText("Usuario: ");

        lblUsuarioActual.setText("label");

        jLabel12.setText("fecha:");

        lblFecha.setText("Usuario: ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarioActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 975, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha)
                .addGap(137, 137, 137))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblFecha)
                    .addComponent(jLabel11)
                    .addComponent(lblUsuarioActual))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
    }//GEN-END:initComponents

    private void btnCancelarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarVentaMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarVentaMouseClicked

    private void btnGuardarNueVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarNueVentaMouseClicked

    }//GEN-LAST:event_btnGuardarNueVentaMouseClicked

  private void txtCodigodeBarraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigodeBarraFocusLost
        preparado();
    }//GEN-LAST:event_txtCodigodeBarraFocusLost

    private void btnAgregarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarArticuloActionPerformed
        GuiArticulos vArt = new GuiArticulos(unaEmpresa);
        vArt.setVisible(true);
    }//GEN-LAST:event_btnAgregarArticuloActionPerformed

    private void txtCodigodeBarraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigodeBarraKeyPressed
       
    }//GEN-LAST:event_txtCodigodeBarraKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtCodigodeBarra.setEnabled(true);
        txtCodigodeBarra.setText("");
        txtPrecio.setText("");
        txtCantidad.setText("");
        jButton1.setEnabled(true);
        txtCodigodeBarra.setEnabled(true);
        lblNombre.setText("");
        lblMarca.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnAgregarEmpleadoActionPerformed
        GuiUsuarios vEmp = new GuiUsuarios(unaEmpresa);//GEN-FIRST:event_btnAgregarEmpleadoActionPerformed
        vEmp.setVisible(true);
    }//GEN-LAST:event_btnAgregarEmpleadoActionPerformed

    private void MenuModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuModificarActionPerformed
        nroFila = tblVenta.getSelectedRow();
        if (nroFila == -1) {
            JOptionPane.showMessageDialog(null, "seleccione una fila");
        } else {
            DefaultTableModel modelo = (DefaultTableModel) tblVenta.getModel();
            txtCantidad.setText(modelo.getValueAt(nroFila, 4).toString());
            txtCodigodeBarra.setText(modelo.getValueAt(nroFila, 0).toString());
            txtPrecio.setText(modelo.getValueAt(nroFila, 5).toString());
            txtCodigodeBarra.setEnabled(false);
            jButton1.setEnabled(false);
            modificar = true;
        } 
    }//GEN-LAST:event_MenuModificarActionPerformed

private void btnCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVentaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarVentaActionPerformed

         
    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (c == '.' && txtPrecio.getText().contains(".")) {
            evt.consume();
        }
        if (txtPrecio.getText().length() >= 7) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtMonto1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMonto1KeyTyped
        char c = evt.getKeyChar();
        double j;
        if (txtMonto1.getText().equals("")) {
            txtMonto1.setText("0.0");
        }
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.')) {
            evt.consume();
        }
        if (c == '.' && txtMonto1.getText().contains(".")) {
            evt.consume();
            int i = txtMonto1.getText().indexOf(".");
            txtMonto1.setCaretPosition(i + 1);
        }
    }//GEN-LAST:event_txtMonto1KeyTyped

    private void txtCodigodeBarraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigodeBarraKeyTyped
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            txtCantidad.requestFocus();
        }
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (txtCodigodeBarra.getText().length() >= 13) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigodeBarraKeyTyped

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
        char c = evt.getKeyChar();
        double j;
        if (txtMonto.getText().equals("")) {
            txtMonto.setText(".0");
        }
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.')) {
            evt.consume();
        } else {
            kill = 0;
        }
        if (c == '.' && txtMonto.getText().contains(".")) {
            evt.consume();
            int i = txtMonto.getText().indexOf(".");
            txtMonto.setCaretPosition(i + 1);
        }
    }//GEN-LAST:event_txtMontoKeyTyped

    private void txtMontoTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtMontoTextValueChanged
        double j = (Double.parseDouble(txtMonto.getText()));
        if (j > Total) {
            txtMonto.setText(String.valueOf(Total));
        }
    }//GEN-LAST:event_txtMontoTextValueChanged

    private void txtDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (txtDoc.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDocKeyTyped

    private void txtMontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoFocusLost
        double j = (Double.parseDouble(txtMonto.getText()));
        if (j > Total) {
            txtMonto.setText(String.valueOf(Total));
        }
    }//GEN-LAST:event_txtMontoFocusLost

    private void txtNomClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomClienteKeyTyped
        if (txtNomCliente.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNomClienteKeyTyped

    private void txtDomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDomKeyTyped
        if (txtDom.getText().length() >= 70) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDomKeyTyped

    private void txtMonto1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMonto1FocusLost
        double j = (Double.parseDouble(txtMonto1.getText()));
        if (j > Total) {
            txtMonto1.setText(String.valueOf(Total));
        }
        lblTotal1.setText(String.valueOf(Double.parseDouble(txtPrecio.getText()) - Double.parseDouble(txtMonto1.getText())));
    }//GEN-LAST:event_txtMonto1FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String unArt = "";
        GuiSeleccionArt filtro = new GuiSeleccionArt(this, true, unaEmpresa, unArt);
        filtro.setVisible(true);
        txtCodigodeBarra.setText(filtro.getUnArt());
        preparado();
        txtCantidad.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MenuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEliminarActionPerformed
        int i = tblVenta.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "seleccione una fila");
        } else {
            DefaultTableModel modelo = (DefaultTableModel) tblVenta.getModel();
            modelo.removeRow(i);
        }
    }//GEN-LAST:event_MenuEliminarActionPerformed

    private void tblVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVentaMouseClicked
        if ((evt.getModifiers() & InputEvent.BUTTON3_MASK) == InputEvent.BUTTON3_MASK) {
            MenuEliminar.setText("Agregar");
            MenuModificar.setText("Modificar");
            jPopupMenu1.add(MenuModificar);
            jPopupMenu1.add(MenuEliminar);
            tblVenta.setComponentPopupMenu(jPopupMenu1);
            jPopupMenu1.setVisible(true);
        }
    }//GEN-LAST:event_tblVentaMouseClicked

    private void btnGuardarNueVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNueVentaActionPerformed
        Guardar();
    }//GEN-LAST:event_btnGuardarNueVentaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (!txtCodigodeBarra.getText().equals("") && (!txtCantidad.getText().equals(""))) {
            CargaTabla();
            txtCodigodeBarra.setEnabled(true);
            if (modificar == true) {
                DefaultTableModel modelo = (DefaultTableModel) tblVenta.getModel();
                modelo.removeRow(tblVenta.getSelectedRow());
                modificar = false;
            }
            txtCantidad.setText("");
            txtPrecio.setText("");
            txtCodigodeBarra.setText("");
            jButton1.setEnabled(true);
            txtCodigodeBarra.setEnabled(true);
            lblNombre.setText("");
            lblMarca.setText("");
            /*if (txtPrecio.getText().equals("")) {
     lblPrecio.setForeground(Color.red);
    } else {
     lblPrecio.setForeground(Color.black);
    }
    if (txtCantidad.getText().equals("")) {
     lblCantidad.setForeground(Color.red);
    } else {
     lblCantidad.setForeground(Color.black);
    }
    if (txtCodigodeBarra.getText().equals("")) {
     lblCodBarra.setForeground(Color.red);
    } else {
     lblCodBarra.setForeground(Color.black);
    }*/
        } else {
            JOptionPane.showMessageDialog(null, "no existe articulos");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtCantidadTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtCantidadTextValueChanged
        int i = Integer.parseInt(txtCantidad.getText());
        if (i > stock)
            txtCantidad.setText(String.valueOf(stock));
    }//GEN-LAST:event_txtCantidadTextValueChanged

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped
    /**
     * @param args the command line arguments
     */
    /*  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
    /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiVenta(unaEmpresa).setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuEliminar;
    private javax.swing.JMenuItem MenuModificar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarArticulo;
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarVenta;
    private javax.swing.JButton btnGuardarNueVenta;
    private javax.swing.JComboBox cmbEmpleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCodBarra;
    private javax.swing.JLabel lblDomCliente;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaVenta;
    private javax.swing.JLabel lblFormaPago4;
    private javax.swing.JLabel lblFormaPago6;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNroDocCliente;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStock2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblUsuarioActual;
    private javax.swing.JPanel panel1;
    private javax.swing.JTable tblVenta;
    private java.awt.TextField txtCantidad;
    private javax.swing.JTextField txtCodigodeBarra;
    private javax.swing.JTextField txtDoc;
    private javax.swing.JTextField txtDom;
    private javax.swing.JFormattedTextField txtFechaVenta;
    private java.awt.TextField txtMonto;
    private java.awt.TextField txtMonto1;
    private javax.swing.JTextField txtNomCliente;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
    public void actualizarComboEmpleado() {
        cmbEmpleado.setModel(new javax.swing.DefaultComboBoxModel(unaEmpresa.getEmpleados().values().toArray()));
    }

    public void CargaTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblVenta.getModel();
        Map articulos = unaEmpresa.getArticulos();
        Articulo unArt = (Articulo) articulos.get(txtCodigodeBarra.getText().toString());
        String detalle = (unArt.getNombre() + " " + unArt.getUnaMarca());
        double total = (Double.parseDouble(txtCantidad.getText()) * Double.parseDouble(txtPrecio.getText()));
        modelo.addRow(new Object[] { (unArt.getCodBarra()), detalle, (unArt.getTalle()), (unArt.getColor()), (txtCantidad.getText()), (lblTotal1.getText()), (total) });
        Double j = 0.0;
        int filas = tblVenta.getRowCount();
        for (int i = 0; filas > i; i++)
            j = j + Double.parseDouble(modelo.getValueAt(i, 6).toString());
        lblTotal.setText(String.valueOf(j));
        Total = j;
    }

    public void Guardar() {
        Calendar fechaActual = new GregorianCalendar().getInstance();
        if ((!txtNomCliente.getText().equals("")) && (!txtNomCliente.getText().equals("")) && (this.tblVenta.getRowCount() != 0)) {
            Empleado unEmpleadocmb;
            unEmpleadocmb = (Empleado) cmbEmpleado.getSelectedItem();
            DefaultTableModel modeloTabla = (DefaultTableModel) tblVenta.getModel();
            //try {
            total = Double.parseDouble(lblTotal.getText());
            fechaVenta = fechaActual;
            nombreCliente = txtNomCliente.getText();
            domCliente = txtDom.getText();
            nroDocCliente = txtDoc.getText();
            unEmpleado = unEmpleadocmb;
            modelo = modeloTabla;
            GuiPago tipoPago = new GuiPago(new javax.swing.JDialog(), true, unaEmpresa, false, Total);
            tipoPago.setVisible(true);
            txtDom.setText("");
            txtNomCliente.setText("");
            txtDoc.setText("");
            int filas = tblVenta.getRowCount();
            for (int i = 0; filas > i; i++)
                modelo.removeRow(0);
        } else {
            if (txtDom.getText().equals("")) {
                lblDomCliente.setForeground(Color.red);
            } else {
                lblDomCliente.setForeground(Color.black);
            }

            if (txtNomCliente.getText().equals("")) {
                lblNombreCliente.setForeground(Color.red);
            } else {
                lblNombreCliente.setForeground(Color.black);
            }
            if (txtDoc.getText().equals("")) {
                lblNroDocCliente.setForeground(Color.red);
            } else {
                lblNroDocCliente.setForeground(Color.black);
            }

        }
    }


    public void run() {
        Thread ct = Thread.currentThread();
        while (ct == hilo) {
            try {
                Calendar c1 = GregorianCalendar.getInstance();
                txtFechaVenta.setText(c1.getTime().toLocaleString());
                lblFecha.setText(c1.getTime().toLocaleString());
                Thread.sleep(500);
            } catch (InterruptedException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }

    public void preparado() {
        if (!txtCodigodeBarra.getText().equals("")) {
            if ((unaEmpresa.getArticulos().containsKey(txtCodigodeBarra.getText()))) {
                DefaultTableModel modelo = (DefaultTableModel) tblVenta.getModel();
                int filas = tblVenta.getRowCount();
                Boolean error = false;
                for (int i = 0; filas > i; i++) {
                    if (txtCodigodeBarra.getText().equals(modelo.getValueAt(i, 0).toString()) && modificar == false) {
                        error = true;
                    }
                }
                if (error) {
                    JOptionPane.showMessageDialog(null, "El articulo ya esta cargado.");
                    txtCodigodeBarra.requestFocus();
                } else {
                    txtCodigodeBarra.setEnabled(false);
                    txtCantidad.setEnabled(true);
                    jButton1.setEnabled(false);
                    Map articulos = unaEmpresa.getArticulos();
                    Articulo unArt = (Articulo) articulos.get(txtCodigodeBarra.getText().toString());
                    btnAgregar.setEnabled(true);
                    lblMarca.setText("Nombre: " + unArt.getNombre());
                    lblMarca.setForeground(Color.green);
                    lblNombre.setText("Marca: " + unArt.getUnaMarca().getNombreMarca());
                    lblNombre.setForeground(Color.green);
                    txtPrecio.setText(String.valueOf(unArt.getPrecioVenta()));
                    txtCantidad.setText("");
                    stock = unArt.getStock();
                    txtMonto1.setText("0.0");
                    lblStock2.setText("la cantidad en stock es " + String.valueOf(stock));
                    lblTotal1.setText(String.valueOf(Double.parseDouble(txtPrecio.getText()) - Double.parseDouble(txtMonto1.getText())));
                }
            } else {
                JOptionPane.showMessageDialog(null, "no existe articulo.");
                lblNombre.setText("no existe articulo");
                lblNombre.setForeground(Color.red);
                lblMarca.setText("");
                btnAgregar.setEnabled(false);
            }
        }
    }
}
